#include <X11/Xcursor/Xcursor.h>

// This file was generated by AutoDynamicHeader: https://github.com/bluesillybeard/AutoDynamicHeader and modified

typedef XcursorImage*(*PFN_XcursorImageCreate)(int width, int height);
typedef void(*PFN_XcursorImageDestroy)(XcursorImage* image);
typedef XcursorImages*(*PFN_XcursorImagesCreate)(int size);
typedef void(*PFN_XcursorImagesDestroy)(XcursorImages* images);
typedef void(*PFN_XcursorImagesSetName)(XcursorImages* images, const char* name);
typedef XcursorCursors*(*PFN_XcursorCursorsCreate)(Display* dpy, int size);
typedef void(*PFN_XcursorCursorsDestroy)(XcursorCursors* cursors);
typedef XcursorAnimate*(*PFN_XcursorAnimateCreate)(XcursorCursors* cursors);
typedef void(*PFN_XcursorAnimateDestroy)(XcursorAnimate* animate);
typedef Cursor(*PFN_XcursorAnimateNext)(XcursorAnimate* animate);
typedef XcursorComment*(*PFN_XcursorCommentCreate)(XcursorUInt comment_type, int length);
typedef void(*PFN_XcursorCommentDestroy)(XcursorComment* comment);
typedef XcursorComments*(*PFN_XcursorCommentsCreate)(int size);
typedef void(*PFN_XcursorCommentsDestroy)(XcursorComments* comments);
typedef XcursorImage*(*PFN_XcursorXcFileLoadImage)(XcursorFile* file, int size);
typedef XcursorImages*(*PFN_XcursorXcFileLoadImages)(XcursorFile* file, int size);
typedef XcursorImages*(*PFN_XcursorXcFileLoadAllImages)(XcursorFile* file);
typedef XcursorBool(*PFN_XcursorXcFileLoad)(XcursorFile* file,
		   XcursorComments** commentsp,
		   XcursorImages** imagesp);
typedef XcursorBool(*PFN_XcursorXcFileSave)(XcursorFile* file,
		   const XcursorComments* comments,
		   const XcursorImages* images);
typedef XcursorImage*(*PFN_XcursorFileLoadImage)(FILE* file, int size);
typedef XcursorImages*(*PFN_XcursorFileLoadImages)(FILE* file, int size);
typedef XcursorImages*(*PFN_XcursorFileLoadAllImages)(FILE* file);
typedef XcursorBool(*PFN_XcursorFileLoad)(FILE* file,
		 XcursorComments** commentsp,
		 XcursorImages** imagesp);
typedef XcursorBool(*PFN_XcursorFileSaveImages)(FILE* file, const XcursorImages* images);
typedef XcursorBool(*PFN_XcursorFileSave)(FILE* 			file,
		 const XcursorComments* comments,
		 const XcursorImages* images);
typedef XcursorImage*(*PFN_XcursorFilenameLoadImage)(const char* filename, int size);
typedef XcursorImages*(*PFN_XcursorFilenameLoadImages)(const char* filename, int size);
typedef XcursorImages*(*PFN_XcursorFilenameLoadAllImages)(const char* filename);
typedef XcursorBool(*PFN_XcursorFilenameLoad)(const char* file,
		     XcursorComments** commentsp,
		     XcursorImages** imagesp);
typedef XcursorBool(*PFN_XcursorFilenameSaveImages)(const char* filename, const XcursorImages* images);
typedef XcursorBool(*PFN_XcursorFilenameSave)(const char* file,
		     const XcursorComments* comments,
		     const XcursorImages* images);
typedef XcursorImage*(*PFN_XcursorLibraryLoadImage)(const char* library, const char* theme, int size);
typedef XcursorImages*(*PFN_XcursorLibraryLoadImages)(const char* library, const char* theme, int size);
typedef char*(*PFN_XcursorLibraryPath)(void);
typedef int(*PFN_XcursorLibraryShape)(const char* library);
typedef Cursor(*PFN_XcursorImageLoadCursor)(Display* dpy, const XcursorImage* image);
typedef XcursorCursors*(*PFN_XcursorImagesLoadCursors)(Display* dpy, const XcursorImages* images);
typedef Cursor(*PFN_XcursorImagesLoadCursor)(Display* dpy, const XcursorImages* images);
typedef Cursor(*PFN_XcursorFilenameLoadCursor)(Display* dpy, const char* file);
typedef XcursorCursors*(*PFN_XcursorFilenameLoadCursors)(Display* dpy, const char* file);
typedef Cursor(*PFN_XcursorLibraryLoadCursor)(Display* dpy, const char* file);
typedef XcursorCursors*(*PFN_XcursorLibraryLoadCursors)(Display* dpy, const char* file);
typedef XcursorImage*(*PFN_XcursorShapeLoadImage)(unsigned int shape, const char* theme, int size);
typedef XcursorImages*(*PFN_XcursorShapeLoadImages)(unsigned int shape, const char* theme, int size);
typedef Cursor(*PFN_XcursorShapeLoadCursor)(Display* dpy, unsigned int shape);
typedef XcursorCursors*(*PFN_XcursorShapeLoadCursors)(Display* dpy, unsigned int shape);
typedef Cursor(*PFN_XcursorTryShapeCursor)(Display* dpy,
		       Font	    source_font,
		       Font	    mask_font,
		       unsigned int source_char,
		       unsigned int mask_char,
		       XColor _Xconst* foreground,
		       XColor _Xconst* background);
typedef void(*PFN_XcursorNoticeCreateBitmap)(Display* dpy,
			   Pixmap	pid,
			   unsigned int width,
			   unsigned int height);
typedef void(*PFN_XcursorNoticePutBitmap)(Display* dpy,
			Drawable    draw,
			XImage* image);
typedef Cursor(*PFN_XcursorTryShapeBitmapCursor)(Display* dpy,
			     Pixmap		source,
			     Pixmap		mask,
			     XColor* foreground,
			     XColor* background,
			     unsigned int	x,
			     unsigned int	y);
typedef void(*PFN_XcursorImageHash)(XImage* image,
		  unsigned char	hash[XCURSOR_BITMAP_HASH_SIZE]);
typedef XcursorBool(*PFN_XcursorSupportsARGB)(Display* dpy);
typedef XcursorBool(*PFN_XcursorSupportsAnim)(Display* dpy);
typedef XcursorBool(*PFN_XcursorSetDefaultSize)(Display* dpy, int size);
typedef int(*PFN_XcursorGetDefaultSize)(Display* dpy);
typedef XcursorBool(*PFN_XcursorSetTheme)(Display* dpy, const char* theme);
typedef char*(*PFN_XcursorGetTheme)(Display* dpy);
typedef XcursorBool(*PFN_XcursorGetThemeCore)(Display* dpy);
typedef XcursorBool(*PFN_XcursorSetThemeCore)(Display* dpy, XcursorBool theme_core);
PFN_XcursorImageCreate src_XcursorImageCreate;
PFN_XcursorImageDestroy src_XcursorImageDestroy;
PFN_XcursorImagesCreate src_XcursorImagesCreate;
PFN_XcursorImagesDestroy src_XcursorImagesDestroy;
PFN_XcursorImagesSetName src_XcursorImagesSetName;
PFN_XcursorCursorsCreate src_XcursorCursorsCreate;
PFN_XcursorCursorsDestroy src_XcursorCursorsDestroy;
PFN_XcursorAnimateCreate src_XcursorAnimateCreate;
PFN_XcursorAnimateDestroy src_XcursorAnimateDestroy;
PFN_XcursorAnimateNext src_XcursorAnimateNext;
PFN_XcursorCommentCreate src_XcursorCommentCreate;
PFN_XcursorCommentDestroy src_XcursorCommentDestroy;
PFN_XcursorCommentsCreate src_XcursorCommentsCreate;
PFN_XcursorCommentsDestroy src_XcursorCommentsDestroy;
PFN_XcursorXcFileLoadImage src_XcursorXcFileLoadImage;
PFN_XcursorXcFileLoadImages src_XcursorXcFileLoadImages;
PFN_XcursorXcFileLoadAllImages src_XcursorXcFileLoadAllImages;
PFN_XcursorXcFileLoad src_XcursorXcFileLoad;
PFN_XcursorXcFileSave src_XcursorXcFileSave;
PFN_XcursorFileLoadImage src_XcursorFileLoadImage;
PFN_XcursorFileLoadImages src_XcursorFileLoadImages;
PFN_XcursorFileLoadAllImages src_XcursorFileLoadAllImages;
PFN_XcursorFileLoad src_XcursorFileLoad;
PFN_XcursorFileSaveImages src_XcursorFileSaveImages;
PFN_XcursorFileSave src_XcursorFileSave;
PFN_XcursorFilenameLoadImage src_XcursorFilenameLoadImage;
PFN_XcursorFilenameLoadImages src_XcursorFilenameLoadImages;
PFN_XcursorFilenameLoadAllImages src_XcursorFilenameLoadAllImages;
PFN_XcursorFilenameLoad src_XcursorFilenameLoad;
PFN_XcursorFilenameSaveImages src_XcursorFilenameSaveImages;
PFN_XcursorFilenameSave src_XcursorFilenameSave;
PFN_XcursorLibraryLoadImage src_XcursorLibraryLoadImage;
PFN_XcursorLibraryLoadImages src_XcursorLibraryLoadImages;
PFN_XcursorLibraryPath src_XcursorLibraryPath;
PFN_XcursorLibraryShape src_XcursorLibraryShape;
PFN_XcursorImageLoadCursor src_XcursorImageLoadCursor;
PFN_XcursorImagesLoadCursors src_XcursorImagesLoadCursors;
PFN_XcursorImagesLoadCursor src_XcursorImagesLoadCursor;
PFN_XcursorFilenameLoadCursor src_XcursorFilenameLoadCursor;
PFN_XcursorFilenameLoadCursors src_XcursorFilenameLoadCursors;
PFN_XcursorLibraryLoadCursor src_XcursorLibraryLoadCursor;
PFN_XcursorLibraryLoadCursors src_XcursorLibraryLoadCursors;
PFN_XcursorShapeLoadImage src_XcursorShapeLoadImage;
PFN_XcursorShapeLoadImages src_XcursorShapeLoadImages;
PFN_XcursorShapeLoadCursor src_XcursorShapeLoadCursor;
PFN_XcursorShapeLoadCursors src_XcursorShapeLoadCursors;
PFN_XcursorTryShapeCursor src_XcursorTryShapeCursor;
PFN_XcursorNoticeCreateBitmap src_XcursorNoticeCreateBitmap;
PFN_XcursorNoticePutBitmap src_XcursorNoticePutBitmap;
PFN_XcursorTryShapeBitmapCursor src_XcursorTryShapeBitmapCursor;
PFN_XcursorImageHash src_XcursorImageHash;
PFN_XcursorSupportsARGB src_XcursorSupportsARGB;
PFN_XcursorSupportsAnim src_XcursorSupportsAnim;
PFN_XcursorSetDefaultSize src_XcursorSetDefaultSize;
PFN_XcursorGetDefaultSize src_XcursorGetDefaultSize;
PFN_XcursorSetTheme src_XcursorSetTheme;
PFN_XcursorGetTheme src_XcursorGetTheme;
PFN_XcursorGetThemeCore src_XcursorGetThemeCore;
PFN_XcursorSetThemeCore src_XcursorSetThemeCore;
#define XcursorImageCreate src_XcursorImageCreate
#define XcursorImageDestroy src_XcursorImageDestroy
#define XcursorImagesCreate src_XcursorImagesCreate
#define XcursorImagesDestroy src_XcursorImagesDestroy
#define XcursorImagesSetName src_XcursorImagesSetName
#define XcursorCursorsCreate src_XcursorCursorsCreate
#define XcursorCursorsDestroy src_XcursorCursorsDestroy
#define XcursorAnimateCreate src_XcursorAnimateCreate
#define XcursorAnimateDestroy src_XcursorAnimateDestroy
#define XcursorAnimateNext src_XcursorAnimateNext
#define XcursorCommentCreate src_XcursorCommentCreate
#define XcursorCommentDestroy src_XcursorCommentDestroy
#define XcursorCommentsCreate src_XcursorCommentsCreate
#define XcursorCommentsDestroy src_XcursorCommentsDestroy
#define XcursorXcFileLoadImage src_XcursorXcFileLoadImage
#define XcursorXcFileLoadImages src_XcursorXcFileLoadImages
#define XcursorXcFileLoadAllImages src_XcursorXcFileLoadAllImages
#define XcursorXcFileLoad src_XcursorXcFileLoad
#define XcursorXcFileSave src_XcursorXcFileSave
#define XcursorFileLoadImage src_XcursorFileLoadImage
#define XcursorFileLoadImages src_XcursorFileLoadImages
#define XcursorFileLoadAllImages src_XcursorFileLoadAllImages
#define XcursorFileLoad src_XcursorFileLoad
#define XcursorFileSaveImages src_XcursorFileSaveImages
#define XcursorFileSave src_XcursorFileSave
#define XcursorFilenameLoadImage src_XcursorFilenameLoadImage
#define XcursorFilenameLoadImages src_XcursorFilenameLoadImages
#define XcursorFilenameLoadAllImages src_XcursorFilenameLoadAllImages
#define XcursorFilenameLoad src_XcursorFilenameLoad
#define XcursorFilenameSaveImages src_XcursorFilenameSaveImages
#define XcursorFilenameSave src_XcursorFilenameSave
#define XcursorLibraryLoadImage src_XcursorLibraryLoadImage
#define XcursorLibraryLoadImages src_XcursorLibraryLoadImages
#define XcursorLibraryPath src_XcursorLibraryPath
#define XcursorLibraryShape src_XcursorLibraryShape
#define XcursorImageLoadCursor src_XcursorImageLoadCursor
#define XcursorImagesLoadCursors src_XcursorImagesLoadCursors
#define XcursorImagesLoadCursor src_XcursorImagesLoadCursor
#define XcursorFilenameLoadCursor src_XcursorFilenameLoadCursor
#define XcursorFilenameLoadCursors src_XcursorFilenameLoadCursors
#define XcursorLibraryLoadCursor src_XcursorLibraryLoadCursor
#define XcursorLibraryLoadCursors src_XcursorLibraryLoadCursors
#define XcursorShapeLoadImage src_XcursorShapeLoadImage
#define XcursorShapeLoadImages src_XcursorShapeLoadImages
#define XcursorShapeLoadCursor src_XcursorShapeLoadCursor
#define XcursorShapeLoadCursors src_XcursorShapeLoadCursors
#define XcursorTryShapeCursor src_XcursorTryShapeCursor
#define XcursorNoticeCreateBitmap src_XcursorNoticeCreateBitmap
#define XcursorNoticePutBitmap src_XcursorNoticePutBitmap
#define XcursorTryShapeBitmapCursor src_XcursorTryShapeBitmapCursor
#define XcursorImageHash src_XcursorImageHash
#define XcursorSupportsARGB src_XcursorSupportsARGB
#define XcursorSupportsAnim src_XcursorSupportsAnim
#define XcursorSetDefaultSize src_XcursorSetDefaultSize
#define XcursorGetDefaultSize src_XcursorGetDefaultSize
#define XcursorSetTheme src_XcursorSetTheme
#define XcursorGetTheme src_XcursorGetTheme
#define XcursorGetThemeCore src_XcursorGetThemeCore
#define XcursorSetThemeCore src_XcursorSetThemeCore
void loadXcursor(void* context, void *(*load_fn)(void* context, const char* name)) {
    src_XcursorImageCreate = (PFN_XcursorImageCreate)load_fn(context, "XcursorImageCreate");
    src_XcursorImageDestroy = (PFN_XcursorImageDestroy)load_fn(context, "XcursorImageDestroy");
    src_XcursorImagesCreate = (PFN_XcursorImagesCreate)load_fn(context, "XcursorImagesCreate");
    src_XcursorImagesDestroy = (PFN_XcursorImagesDestroy)load_fn(context, "XcursorImagesDestroy");
    src_XcursorImagesSetName = (PFN_XcursorImagesSetName)load_fn(context, "XcursorImagesSetName");
    src_XcursorCursorsCreate = (PFN_XcursorCursorsCreate)load_fn(context, "XcursorCursorsCreate");
    src_XcursorCursorsDestroy = (PFN_XcursorCursorsDestroy)load_fn(context, "XcursorCursorsDestroy");
    src_XcursorAnimateCreate = (PFN_XcursorAnimateCreate)load_fn(context, "XcursorAnimateCreate");
    src_XcursorAnimateDestroy = (PFN_XcursorAnimateDestroy)load_fn(context, "XcursorAnimateDestroy");
    src_XcursorAnimateNext = (PFN_XcursorAnimateNext)load_fn(context, "XcursorAnimateNext");
    src_XcursorCommentCreate = (PFN_XcursorCommentCreate)load_fn(context, "XcursorCommentCreate");
    src_XcursorCommentDestroy = (PFN_XcursorCommentDestroy)load_fn(context, "XcursorCommentDestroy");
    src_XcursorCommentsCreate = (PFN_XcursorCommentsCreate)load_fn(context, "XcursorCommentsCreate");
    src_XcursorCommentsDestroy = (PFN_XcursorCommentsDestroy)load_fn(context, "XcursorCommentsDestroy");
    src_XcursorXcFileLoadImage = (PFN_XcursorXcFileLoadImage)load_fn(context, "XcursorXcFileLoadImage");
    src_XcursorXcFileLoadImages = (PFN_XcursorXcFileLoadImages)load_fn(context, "XcursorXcFileLoadImages");
    src_XcursorXcFileLoadAllImages = (PFN_XcursorXcFileLoadAllImages)load_fn(context, "XcursorXcFileLoadAllImages");
    src_XcursorXcFileLoad = (PFN_XcursorXcFileLoad)load_fn(context, "XcursorXcFileLoad");
    src_XcursorXcFileSave = (PFN_XcursorXcFileSave)load_fn(context, "XcursorXcFileSave");
    src_XcursorFileLoadImage = (PFN_XcursorFileLoadImage)load_fn(context, "XcursorFileLoadImage");
    src_XcursorFileLoadImages = (PFN_XcursorFileLoadImages)load_fn(context, "XcursorFileLoadImages");
    src_XcursorFileLoadAllImages = (PFN_XcursorFileLoadAllImages)load_fn(context, "XcursorFileLoadAllImages");
    src_XcursorFileLoad = (PFN_XcursorFileLoad)load_fn(context, "XcursorFileLoad");
    src_XcursorFileSaveImages = (PFN_XcursorFileSaveImages)load_fn(context, "XcursorFileSaveImages");
    src_XcursorFileSave = (PFN_XcursorFileSave)load_fn(context, "XcursorFileSave");
    src_XcursorFilenameLoadImage = (PFN_XcursorFilenameLoadImage)load_fn(context, "XcursorFilenameLoadImage");
    src_XcursorFilenameLoadImages = (PFN_XcursorFilenameLoadImages)load_fn(context, "XcursorFilenameLoadImages");
    src_XcursorFilenameLoadAllImages = (PFN_XcursorFilenameLoadAllImages)load_fn(context, "XcursorFilenameLoadAllImages");
    src_XcursorFilenameLoad = (PFN_XcursorFilenameLoad)load_fn(context, "XcursorFilenameLoad");
    src_XcursorFilenameSaveImages = (PFN_XcursorFilenameSaveImages)load_fn(context, "XcursorFilenameSaveImages");
    src_XcursorFilenameSave = (PFN_XcursorFilenameSave)load_fn(context, "XcursorFilenameSave");
    src_XcursorLibraryLoadImage = (PFN_XcursorLibraryLoadImage)load_fn(context, "XcursorLibraryLoadImage");
    src_XcursorLibraryLoadImages = (PFN_XcursorLibraryLoadImages)load_fn(context, "XcursorLibraryLoadImages");
    src_XcursorLibraryPath = (PFN_XcursorLibraryPath)load_fn(context, "XcursorLibraryPath");
    src_XcursorLibraryShape = (PFN_XcursorLibraryShape)load_fn(context, "XcursorLibraryShape");
    src_XcursorImageLoadCursor = (PFN_XcursorImageLoadCursor)load_fn(context, "XcursorImageLoadCursor");
    src_XcursorImagesLoadCursors = (PFN_XcursorImagesLoadCursors)load_fn(context, "XcursorImagesLoadCursors");
    src_XcursorImagesLoadCursor = (PFN_XcursorImagesLoadCursor)load_fn(context, "XcursorImagesLoadCursor");
    src_XcursorFilenameLoadCursor = (PFN_XcursorFilenameLoadCursor)load_fn(context, "XcursorFilenameLoadCursor");
    src_XcursorFilenameLoadCursors = (PFN_XcursorFilenameLoadCursors)load_fn(context, "XcursorFilenameLoadCursors");
    src_XcursorLibraryLoadCursor = (PFN_XcursorLibraryLoadCursor)load_fn(context, "XcursorLibraryLoadCursor");
    src_XcursorLibraryLoadCursors = (PFN_XcursorLibraryLoadCursors)load_fn(context, "XcursorLibraryLoadCursors");
    src_XcursorShapeLoadImage = (PFN_XcursorShapeLoadImage)load_fn(context, "XcursorShapeLoadImage");
    src_XcursorShapeLoadImages = (PFN_XcursorShapeLoadImages)load_fn(context, "XcursorShapeLoadImages");
    src_XcursorShapeLoadCursor = (PFN_XcursorShapeLoadCursor)load_fn(context, "XcursorShapeLoadCursor");
    src_XcursorShapeLoadCursors = (PFN_XcursorShapeLoadCursors)load_fn(context, "XcursorShapeLoadCursors");
    src_XcursorTryShapeCursor = (PFN_XcursorTryShapeCursor)load_fn(context, "XcursorTryShapeCursor");
    src_XcursorNoticeCreateBitmap = (PFN_XcursorNoticeCreateBitmap)load_fn(context, "XcursorNoticeCreateBitmap");
    src_XcursorNoticePutBitmap = (PFN_XcursorNoticePutBitmap)load_fn(context, "XcursorNoticePutBitmap");
    src_XcursorTryShapeBitmapCursor = (PFN_XcursorTryShapeBitmapCursor)load_fn(context, "XcursorTryShapeBitmapCursor");
    src_XcursorImageHash = (PFN_XcursorImageHash)load_fn(context, "XcursorImageHash");
    src_XcursorSupportsARGB = (PFN_XcursorSupportsARGB)load_fn(context, "XcursorSupportsARGB");
    src_XcursorSupportsAnim = (PFN_XcursorSupportsAnim)load_fn(context, "XcursorSupportsAnim");
    src_XcursorSetDefaultSize = (PFN_XcursorSetDefaultSize)load_fn(context, "XcursorSetDefaultSize");
    src_XcursorGetDefaultSize = (PFN_XcursorGetDefaultSize)load_fn(context, "XcursorGetDefaultSize");
    src_XcursorSetTheme = (PFN_XcursorSetTheme)load_fn(context, "XcursorSetTheme");
    src_XcursorGetTheme = (PFN_XcursorGetTheme)load_fn(context, "XcursorGetTheme");
    src_XcursorGetThemeCore = (PFN_XcursorGetThemeCore)load_fn(context, "XcursorGetThemeCore");
    src_XcursorSetThemeCore = (PFN_XcursorSetThemeCore)load_fn(context, "XcursorSetThemeCore");
}