#include <X11/Xlib.h>

// This file was generated by AutoDynamicHeader: https://github.com/bluesillybeard/AutoDynamicHeader

typedef int(*PFN__Xmblen)(
    char *str,
    int len
    );
typedef XFontStruct*(*PFN_XLoadQueryFont)(
    Display*		,
    _Xconst char*	
);
typedef XFontStruct*(*PFN_XQueryFont)(
    Display*		,
    XID			
);
typedef XTimeCoord*(*PFN_XGetMotionEvents)(
    Display*		,
    Window		,
    Time		,
    Time		,
    int*		
);
typedef XModifierKeymap*(*PFN_XDeleteModifiermapEntry)(
    XModifierKeymap*	,
#if NeedWidePrototypes
    unsigned int	,
#else
    KeyCode		,
#endif
    int			
);
typedef XModifierKeymap*(*PFN_XGetModifierMapping)(
    Display*		
);
typedef XModifierKeymap*(*PFN_XInsertModifiermapEntry)(
    XModifierKeymap*	,
#if NeedWidePrototypes
    unsigned int	,
#else
    KeyCode		,
#endif
    int			
);
typedef XModifierKeymap*(*PFN_XNewModifiermap)(
    int			
);
typedef XImage*(*PFN_XCreateImage)(
    Display*		,
    Visual*		,
    unsigned int	,
    int			,
    int			,
    char*		,
    unsigned int	,
    unsigned int	,
    int			,
    int			
);
typedef Status(*PFN_XInitImage)(
    XImage*		
);
typedef XImage*(*PFN_XGetImage)(
    Display*		,
    Drawable		,
    int			,
    int			,
    unsigned int	,
    unsigned int	,
    unsigned long	,
    int			
);
typedef XImage*(*PFN_XGetSubImage)(
    Display*		,
    Drawable		,
    int			,
    int			,
    unsigned int	,
    unsigned int	,
    unsigned long	,
    int			,
    XImage*		,
    int			,
    int			
);
typedef Display*(*PFN_XOpenDisplay)(
    _Xconst char*	
);
typedef void(*PFN_XrmInitialize)(
    void
);
typedef char*(*PFN_XFetchBytes)(
    Display*		,
    int*		
);
typedef char*(*PFN_XFetchBuffer)(
    Display*		,
    int*		,
    int			
);
typedef char*(*PFN_XGetAtomName)(
    Display*		,
    Atom		
);
typedef Status(*PFN_XGetAtomNames)(
    Display*		,
    Atom*		,
    int			,
    char**		
);
typedef char*(*PFN_XGetDefault)(
    Display*		,
    _Xconst char*	,
    _Xconst char*	
);
typedef char*(*PFN_XDisplayName)(
    _Xconst char*	
);
typedef char*(*PFN_XKeysymToString)(
    KeySym		
);
typedef Atom(*PFN_XInternAtom)(
    Display*		,
    _Xconst char*	,
    Bool		
);
typedef Status(*PFN_XInternAtoms)(
    Display*		,
    char**		,
    int			,
    Bool		,
    Atom*		
);
typedef Colormap(*PFN_XCopyColormapAndFree)(
    Display*		,
    Colormap		
);
typedef Colormap(*PFN_XCreateColormap)(
    Display*		,
    Window		,
    Visual*		,
    int			
);
typedef Cursor(*PFN_XCreatePixmapCursor)(
    Display*		,
    Pixmap		,
    Pixmap		,
    XColor*		,
    XColor*		,
    unsigned int	,
    unsigned int	
);
typedef Cursor(*PFN_XCreateGlyphCursor)(
    Display*		,
    Font		,
    Font		,
    unsigned int	,
    unsigned int	,
    XColor _Xconst *	,
    XColor _Xconst *	
);
typedef Cursor(*PFN_XCreateFontCursor)(
    Display*		,
    unsigned int	
);
typedef Font(*PFN_XLoadFont)(
    Display*		,
    _Xconst char*	
);
typedef GC(*PFN_XCreateGC)(
    Display*		,
    Drawable		,
    unsigned long	,
    XGCValues*		
);
typedef GContext(*PFN_XGContextFromGC)(
    GC			
);
typedef void(*PFN_XFlushGC)(
    Display*		,
    GC			
);
typedef Pixmap(*PFN_XCreatePixmap)(
    Display*		,
    Drawable		,
    unsigned int	,
    unsigned int	,
    unsigned int	
);
typedef Pixmap(*PFN_XCreateBitmapFromData)(
    Display*		,
    Drawable		,
    _Xconst char*	,
    unsigned int	,
    unsigned int	
);
typedef Pixmap(*PFN_XCreatePixmapFromBitmapData)(
    Display*		,
    Drawable		,
    char*		,
    unsigned int	,
    unsigned int	,
    unsigned long	,
    unsigned long	,
    unsigned int	
);
typedef Window(*PFN_XCreateSimpleWindow)(
    Display*		,
    Window		,
    int			,
    int			,
    unsigned int	,
    unsigned int	,
    unsigned int	,
    unsigned long	,
    unsigned long	
);
typedef Window(*PFN_XGetSelectionOwner)(
    Display*		,
    Atom		
);
typedef Window(*PFN_XCreateWindow)(
    Display*		,
    Window		,
    int			,
    int			,
    unsigned int	,
    unsigned int	,
    unsigned int	,
    int			,
    unsigned int	,
    Visual*		,
    unsigned long	,
    XSetWindowAttributes*	
);
typedef Colormap*(*PFN_XListInstalledColormaps)(
    Display*		,
    Window		,
    int*		
);
typedef char**(*PFN_XListFonts)(
    Display*		,
    _Xconst char*	,
    int			,
    int*		
);
typedef char**(*PFN_XListFontsWithInfo)(
    Display*		,
    _Xconst char*	,
    int			,
    int*		,
    XFontStruct**	
);
typedef char**(*PFN_XGetFontPath)(
    Display*		,
    int*		
);
typedef char**(*PFN_XListExtensions)(
    Display*		,
    int*		
);
typedef Atom*(*PFN_XListProperties)(
    Display*		,
    Window		,
    int*		
);
typedef XHostAddress*(*PFN_XListHosts)(
    Display*		,
    int*		,
    Bool*		
);
typedef KeySym(*PFN_XKeycodeToKeysym)(
    Display*		,
#if NeedWidePrototypes
    unsigned int	,
#else
    KeyCode		,
#endif
    int			
);
typedef KeySym(*PFN_XLookupKeysym)(
    XKeyEvent*		,
    int			
);
typedef KeySym*(*PFN_XGetKeyboardMapping)(
    Display*		,
#if NeedWidePrototypes
    unsigned int	,
#else
    KeyCode		,
#endif
    int			,
    int*		
);
typedef KeySym(*PFN_XStringToKeysym)(
    _Xconst char*	
);
typedef long(*PFN_XMaxRequestSize)(
    Display*		
);
typedef long(*PFN_XExtendedMaxRequestSize)(
    Display*		
);
typedef char*(*PFN_XResourceManagerString)(
    Display*		
);
typedef char*(*PFN_XScreenResourceString)(
	Screen*		
);
typedef long(*PFN_XDisplayMotionBufferSize)(
    Display*		
);
typedef VisualID(*PFN_XVisualIDFromVisual)(
    Visual*		
);
typedef Status(*PFN_XInitThreads)(
    void
);
typedef void(*PFN_XLockDisplay)(
    Display*		
);
typedef void(*PFN_XUnlockDisplay)(
    Display*		
);
typedef XExtCodes*(*PFN_XInitExtension)(
    Display*		,
    _Xconst char*	
);
typedef XExtCodes*(*PFN_XAddExtension)(
    Display*		
);
typedef XExtData*(*PFN_XFindOnExtensionList)(
    XExtData**		,
    int			
);
typedef XExtData**(*PFN_XEHeadOfExtensionList)(
    XEDataObject	
);
typedef Window(*PFN_XRootWindow)(
    Display*		,
    int			
);
typedef Window(*PFN_XDefaultRootWindow)(
    Display*		
);
typedef Window(*PFN_XRootWindowOfScreen)(
    Screen*		
);
typedef Visual*(*PFN_XDefaultVisual)(
    Display*		,
    int			
);
typedef Visual*(*PFN_XDefaultVisualOfScreen)(
    Screen*		
);
typedef GC(*PFN_XDefaultGC)(
    Display*		,
    int			
);
typedef GC(*PFN_XDefaultGCOfScreen)(
    Screen*		
);
typedef long(*PFN_XBlackPixel)(
    Display*		,
    int			
);
typedef long(*PFN_XWhitePixel)(
    Display*		,
    int			
);
typedef long(*PFN_XAllPlanes)(
    void
);
typedef long(*PFN_XBlackPixelOfScreen)(
    Screen*		
);
typedef long(*PFN_XWhitePixelOfScreen)(
    Screen*		
);
typedef long(*PFN_XNextRequest)(
    Display*		
);
typedef long(*PFN_XLastKnownRequestProcessed)(
    Display*		
);
typedef char*(*PFN_XServerVendor)(
    Display*		
);
typedef char*(*PFN_XDisplayString)(
    Display*		
);
typedef Colormap(*PFN_XDefaultColormap)(
    Display*		,
    int			
);
typedef Colormap(*PFN_XDefaultColormapOfScreen)(
    Screen*		
);
typedef Display*(*PFN_XDisplayOfScreen)(
    Screen*		
);
typedef Screen*(*PFN_XScreenOfDisplay)(
    Display*		,
    int			
);
typedef Screen*(*PFN_XDefaultScreenOfDisplay)(
    Display*		
);
typedef long(*PFN_XEventMaskOfScreen)(
    Screen*		
);
typedef int(*PFN_XScreenNumberOfScreen)(
    Screen*		
);
typedef XErrorHandler(*PFN_XSetErrorHandler)(
    XErrorHandler	
);
typedef XIOErrorHandler(*PFN_XSetIOErrorHandler)(
    XIOErrorHandler	
);
typedef void(*PFN_XSetIOErrorExitHandler)(
    Display*,			
    XIOErrorExitHandler,	
    void*			
);
typedef XPixmapFormatValues*(*PFN_XListPixmapFormats)(
    Display*		,
    int*		
);
typedef int*(*PFN_XListDepths)(
    Display*		,
    int			,
    int*		
);
typedef Status(*PFN_XReconfigureWMWindow)(
    Display*		,
    Window		,
    int			,
    unsigned int	,
    XWindowChanges*	
);
typedef Status(*PFN_XGetWMProtocols)(
    Display*		,
    Window		,
    Atom**		,
    int*		
);
typedef Status(*PFN_XSetWMProtocols)(
    Display*		,
    Window		,
    Atom*		,
    int			
);
typedef Status(*PFN_XIconifyWindow)(
    Display*		,
    Window		,
    int			
);
typedef Status(*PFN_XWithdrawWindow)(
    Display*		,
    Window		,
    int			
);
typedef Status(*PFN_XGetCommand)(
    Display*		,
    Window		,
    char***		,
    int*		
);
typedef Status(*PFN_XGetWMColormapWindows)(
    Display*		,
    Window		,
    Window**		,
    int*		
);
typedef Status(*PFN_XSetWMColormapWindows)(
    Display*		,
    Window		,
    Window*		,
    int			
);
typedef void(*PFN_XFreeStringList)(
    char**		
);
typedef int(*PFN_XSetTransientForHint)(
    Display*		,
    Window		,
    Window		
);
typedef int(*PFN_XActivateScreenSaver)(
    Display*		
);
typedef int(*PFN_XAddHost)(
    Display*		,
    XHostAddress*	
);
typedef int(*PFN_XAddHosts)(
    Display*		,
    XHostAddress*	,
    int			
);
typedef int(*PFN_XAddToExtensionList)(
    struct _XExtData**	,
    XExtData*		
);
typedef int(*PFN_XAddToSaveSet)(
    Display*		,
    Window		
);
typedef Status(*PFN_XAllocColor)(
    Display*		,
    Colormap		,
    XColor*		
);
typedef Status(*PFN_XAllocColorCells)(
    Display*		,
    Colormap		,
    Bool	        ,
    unsigned long*	,
    unsigned int	,
    unsigned long*	,
    unsigned int 	
);
typedef Status(*PFN_XAllocColorPlanes)(
    Display*		,
    Colormap		,
    Bool		,
    unsigned long*	,
    int			,
    int			,
    int			,
    int			,
    unsigned long*	,
    unsigned long*	,
    unsigned long*	
);
typedef Status(*PFN_XAllocNamedColor)(
    Display*		,
    Colormap		,
    _Xconst char*	,
    XColor*		,
    XColor*		
);
typedef int(*PFN_XAllowEvents)(
    Display*		,
    int			,
    Time		
);
typedef int(*PFN_XAutoRepeatOff)(
    Display*		
);
typedef int(*PFN_XAutoRepeatOn)(
    Display*		
);
typedef int(*PFN_XBell)(
    Display*		,
    int			
);
typedef int(*PFN_XBitmapBitOrder)(
    Display*		
);
typedef int(*PFN_XBitmapPad)(
    Display*		
);
typedef int(*PFN_XBitmapUnit)(
    Display*		
);
typedef int(*PFN_XCellsOfScreen)(
    Screen*		
);
typedef int(*PFN_XChangeActivePointerGrab)(
    Display*		,
    unsigned int	,
    Cursor		,
    Time		
);
typedef int(*PFN_XChangeGC)(
    Display*		,
    GC			,
    unsigned long	,
    XGCValues*		
);
typedef int(*PFN_XChangeKeyboardControl)(
    Display*		,
    unsigned long	,
    XKeyboardControl*	
);
typedef int(*PFN_XChangeKeyboardMapping)(
    Display*		,
    int			,
    int			,
    KeySym*		,
    int			
);
typedef int(*PFN_XChangePointerControl)(
    Display*		,
    Bool		,
    Bool		,
    int			,
    int			,
    int			
);
typedef int(*PFN_XChangeProperty)(
    Display*		,
    Window		,
    Atom		,
    Atom		,
    int			,
    int			,
    _Xconst unsigned char*	,
    int			
);
typedef int(*PFN_XChangeSaveSet)(
    Display*		,
    Window		,
    int			
);
typedef int(*PFN_XChangeWindowAttributes)(
    Display*		,
    Window		,
    unsigned long	,
    XSetWindowAttributes* 
);
typedef Bool(*PFN_XCheckMaskEvent)(
    Display*		,
    long		,
    XEvent*		
);
typedef Bool(*PFN_XCheckTypedEvent)(
    Display*		,
    int			,
    XEvent*		
);
typedef Bool(*PFN_XCheckTypedWindowEvent)(
    Display*		,
    Window		,
    int			,
    XEvent*		
);
typedef Bool(*PFN_XCheckWindowEvent)(
    Display*		,
    Window		,
    long		,
    XEvent*		
);
typedef int(*PFN_XCirculateSubwindows)(
    Display*		,
    Window		,
    int			
);
typedef int(*PFN_XCirculateSubwindowsDown)(
    Display*		,
    Window		
);
typedef int(*PFN_XCirculateSubwindowsUp)(
    Display*		,
    Window		
);
typedef int(*PFN_XClearArea)(
    Display*		,
    Window		,
    int			,
    int			,
    unsigned int	,
    unsigned int	,
    Bool		
);
typedef int(*PFN_XClearWindow)(
    Display*		,
    Window		
);
typedef int(*PFN_XCloseDisplay)(
    Display*		
);
typedef int(*PFN_XConfigureWindow)(
    Display*		,
    Window		,
    unsigned int	,
    XWindowChanges*	
);
typedef int(*PFN_XConnectionNumber)(
    Display*		
);
typedef int(*PFN_XConvertSelection)(
    Display*		,
    Atom		,
    Atom 		,
    Atom		,
    Window		,
    Time		
);
typedef int(*PFN_XCopyArea)(
    Display*		,
    Drawable		,
    Drawable		,
    GC			,
    int			,
    int			,
    unsigned int	,
    unsigned int	,
    int			,
    int			
);
typedef int(*PFN_XCopyGC)(
    Display*		,
    GC			,
    unsigned long	,
    GC			
);
typedef int(*PFN_XCopyPlane)(
    Display*		,
    Drawable		,
    Drawable		,
    GC			,
    int			,
    int			,
    unsigned int	,
    unsigned int	,
    int			,
    int			,
    unsigned long	
);
typedef int(*PFN_XDefaultDepth)(
    Display*		,
    int			
);
typedef int(*PFN_XDefaultDepthOfScreen)(
    Screen*		
);
typedef int(*PFN_XDefaultScreen)(
    Display*		
);
typedef int(*PFN_XDefineCursor)(
    Display*		,
    Window		,
    Cursor		
);
typedef int(*PFN_XDeleteProperty)(
    Display*		,
    Window		,
    Atom		
);
typedef int(*PFN_XDestroyWindow)(
    Display*		,
    Window		
);
typedef int(*PFN_XDestroySubwindows)(
    Display*		,
    Window		
);
typedef int(*PFN_XDoesBackingStore)(
    Screen*		
);
typedef Bool(*PFN_XDoesSaveUnders)(
    Screen*		
);
typedef int(*PFN_XDisableAccessControl)(
    Display*		
);
typedef int(*PFN_XDisplayCells)(
    Display*		,
    int			
);
typedef int(*PFN_XDisplayHeight)(
    Display*		,
    int			
);
typedef int(*PFN_XDisplayHeightMM)(
    Display*		,
    int			
);
typedef int(*PFN_XDisplayKeycodes)(
    Display*		,
    int*		,
    int*		
);
typedef int(*PFN_XDisplayPlanes)(
    Display*		,
    int			
);
typedef int(*PFN_XDisplayWidth)(
    Display*		,
    int			
);
typedef int(*PFN_XDisplayWidthMM)(
    Display*		,
    int			
);
typedef int(*PFN_XDrawArc)(
    Display*		,
    Drawable		,
    GC			,
    int			,
    int			,
    unsigned int	,
    unsigned int	,
    int			,
    int			
);
typedef int(*PFN_XDrawArcs)(
    Display*		,
    Drawable		,
    GC			,
    XArc*		,
    int			
);
typedef int(*PFN_XDrawImageString)(
    Display*		,
    Drawable		,
    GC			,
    int			,
    int			,
    _Xconst char*	,
    int			
);
typedef int(*PFN_XDrawImageString16)(
    Display*		,
    Drawable		,
    GC			,
    int			,
    int			,
    _Xconst XChar2b*	,
    int			
);
typedef int(*PFN_XDrawLine)(
    Display*		,
    Drawable		,
    GC			,
    int			,
    int			,
    int			,
    int			
);
typedef int(*PFN_XDrawLines)(
    Display*		,
    Drawable		,
    GC			,
    XPoint*		,
    int			,
    int			
);
typedef int(*PFN_XDrawPoint)(
    Display*		,
    Drawable		,
    GC			,
    int			,
    int			
);
typedef int(*PFN_XDrawPoints)(
    Display*		,
    Drawable		,
    GC			,
    XPoint*		,
    int			,
    int			
);
typedef int(*PFN_XDrawRectangle)(
    Display*		,
    Drawable		,
    GC			,
    int			,
    int			,
    unsigned int	,
    unsigned int	
);
typedef int(*PFN_XDrawRectangles)(
    Display*		,
    Drawable		,
    GC			,
    XRectangle*		,
    int			
);
typedef int(*PFN_XDrawSegments)(
    Display*		,
    Drawable		,
    GC			,
    XSegment*		,
    int			
);
typedef int(*PFN_XDrawString)(
    Display*		,
    Drawable		,
    GC			,
    int			,
    int			,
    _Xconst char*	,
    int			
);
typedef int(*PFN_XDrawString16)(
    Display*		,
    Drawable		,
    GC			,
    int			,
    int			,
    _Xconst XChar2b*	,
    int			
);
typedef int(*PFN_XDrawText)(
    Display*		,
    Drawable		,
    GC			,
    int			,
    int			,
    XTextItem*		,
    int			
);
typedef int(*PFN_XDrawText16)(
    Display*		,
    Drawable		,
    GC			,
    int			,
    int			,
    XTextItem16*	,
    int			
);
typedef int(*PFN_XEnableAccessControl)(
    Display*		
);
typedef int(*PFN_XEventsQueued)(
    Display*		,
    int			
);
typedef Status(*PFN_XFetchName)(
    Display*		,
    Window		,
    char**		
);
typedef int(*PFN_XFillArc)(
    Display*		,
    Drawable		,
    GC			,
    int			,
    int			,
    unsigned int	,
    unsigned int	,
    int			,
    int			
);
typedef int(*PFN_XFillArcs)(
    Display*		,
    Drawable		,
    GC			,
    XArc*		,
    int			
);
typedef int(*PFN_XFillPolygon)(
    Display*		,
    Drawable		,
    GC			,
    XPoint*		,
    int			,
    int			,
    int			
);
typedef int(*PFN_XFillRectangle)(
    Display*		,
    Drawable		,
    GC			,
    int			,
    int			,
    unsigned int	,
    unsigned int	
);
typedef int(*PFN_XFillRectangles)(
    Display*		,
    Drawable		,
    GC			,
    XRectangle*		,
    int			
);
typedef int(*PFN_XFlush)(
    Display*		
);
typedef int(*PFN_XForceScreenSaver)(
    Display*		,
    int			
);
typedef int(*PFN_XFree)(
    void*		
);
typedef int(*PFN_XFreeColormap)(
    Display*		,
    Colormap		
);
typedef int(*PFN_XFreeColors)(
    Display*		,
    Colormap		,
    unsigned long*	,
    int			,
    unsigned long	
);
typedef int(*PFN_XFreeCursor)(
    Display*		,
    Cursor		
);
typedef int(*PFN_XFreeExtensionList)(
    char**		
);
typedef int(*PFN_XFreeFont)(
    Display*		,
    XFontStruct*	
);
typedef int(*PFN_XFreeFontInfo)(
    char**		,
    XFontStruct*	,
    int			
);
typedef int(*PFN_XFreeFontNames)(
    char**		
);
typedef int(*PFN_XFreeFontPath)(
    char**		
);
typedef int(*PFN_XFreeGC)(
    Display*		,
    GC			
);
typedef int(*PFN_XFreeModifiermap)(
    XModifierKeymap*	
);
typedef int(*PFN_XFreePixmap)(
    Display*		,
    Pixmap		
);
typedef int(*PFN_XGeometry)(
    Display*		,
    int			,
    _Xconst char*	,
    _Xconst char*	,
    unsigned int	,
    unsigned int	,
    unsigned int	,
    int			,
    int			,
    int*		,
    int*		,
    int*		,
    int*		
);
typedef int(*PFN_XGetErrorDatabaseText)(
    Display*		,
    _Xconst char*	,
    _Xconst char*	,
    _Xconst char*	,
    char*		,
    int			
);
typedef int(*PFN_XGetErrorText)(
    Display*		,
    int			,
    char*		,
    int			
);
typedef Bool(*PFN_XGetFontProperty)(
    XFontStruct*	,
    Atom		,
    unsigned long*	
);
typedef Status(*PFN_XGetGCValues)(
    Display*		,
    GC			,
    unsigned long	,
    XGCValues*		
);
typedef Status(*PFN_XGetGeometry)(
    Display*		,
    Drawable		,
    Window*		,
    int*		,
    int*		,
    unsigned int*	,
    unsigned int*	,
    unsigned int*	,
    unsigned int*	
);
typedef Status(*PFN_XGetIconName)(
    Display*		,
    Window		,
    char**		
);
typedef int(*PFN_XGetInputFocus)(
    Display*		,
    Window*		,
    int*		
);
typedef int(*PFN_XGetKeyboardControl)(
    Display*		,
    XKeyboardState*	
);
typedef int(*PFN_XGetPointerControl)(
    Display*		,
    int*		,
    int*		,
    int*		
);
typedef int(*PFN_XGetPointerMapping)(
    Display*		,
    unsigned char*	,
    int			
);
typedef int(*PFN_XGetScreenSaver)(
    Display*		,
    int*		,
    int*		,
    int*		,
    int*		
);
typedef Status(*PFN_XGetTransientForHint)(
    Display*		,
    Window		,
    Window*		
);
typedef int(*PFN_XGetWindowProperty)(
    Display*		,
    Window		,
    Atom		,
    long		,
    long		,
    Bool		,
    Atom		,
    Atom*		,
    int*		,
    unsigned long*	,
    unsigned long*	,
    unsigned char**	
);
typedef Status(*PFN_XGetWindowAttributes)(
    Display*		,
    Window		,
    XWindowAttributes*	
);
typedef int(*PFN_XGrabButton)(
    Display*		,
    unsigned int	,
    unsigned int	,
    Window		,
    Bool		,
    unsigned int	,
    int			,
    int			,
    Window		,
    Cursor		
);
typedef int(*PFN_XGrabKey)(
    Display*		,
    int			,
    unsigned int	,
    Window		,
    Bool		,
    int			,
    int			
);
typedef int(*PFN_XGrabKeyboard)(
    Display*		,
    Window		,
    Bool		,
    int			,
    int			,
    Time		
);
typedef int(*PFN_XGrabPointer)(
    Display*		,
    Window		,
    Bool		,
    unsigned int	,
    int			,
    int			,
    Window		,
    Cursor		,
    Time		
);
typedef int(*PFN_XGrabServer)(
    Display*		
);
typedef int(*PFN_XHeightMMOfScreen)(
    Screen*		
);
typedef int(*PFN_XHeightOfScreen)(
    Screen*		
);
typedef int(*PFN_XImageByteOrder)(
    Display*		
);
typedef int(*PFN_XInstallColormap)(
    Display*		,
    Colormap		
);
typedef KeyCode(*PFN_XKeysymToKeycode)(
    Display*		,
    KeySym		
);
typedef int(*PFN_XKillClient)(
    Display*		,
    XID			
);
typedef Status(*PFN_XLookupColor)(
    Display*		,
    Colormap		,
    _Xconst char*	,
    XColor*		,
    XColor*		
);
typedef int(*PFN_XLowerWindow)(
    Display*		,
    Window		
);
typedef int(*PFN_XMapRaised)(
    Display*		,
    Window		
);
typedef int(*PFN_XMapSubwindows)(
    Display*		,
    Window		
);
typedef int(*PFN_XMapWindow)(
    Display*		,
    Window		
);
typedef int(*PFN_XMaskEvent)(
    Display*		,
    long		,
    XEvent*		
);
typedef int(*PFN_XMaxCmapsOfScreen)(
    Screen*		
);
typedef int(*PFN_XMinCmapsOfScreen)(
    Screen*		
);
typedef int(*PFN_XMoveResizeWindow)(
    Display*		,
    Window		,
    int			,
    int			,
    unsigned int	,
    unsigned int	
);
typedef int(*PFN_XMoveWindow)(
    Display*		,
    Window		,
    int			,
    int			
);
typedef int(*PFN_XNextEvent)(
    Display*		,
    XEvent*		
);
typedef int(*PFN_XNoOp)(
    Display*		
);
typedef Status(*PFN_XParseColor)(
    Display*		,
    Colormap		,
    _Xconst char*	,
    XColor*		
);
typedef int(*PFN_XParseGeometry)(
    _Xconst char*	,
    int*		,
    int*		,
    unsigned int*	,
    unsigned int*	
);
typedef int(*PFN_XPeekEvent)(
    Display*		,
    XEvent*		
);
typedef int(*PFN_XPending)(
    Display*		
);
typedef int(*PFN_XPlanesOfScreen)(
    Screen*		
);
typedef int(*PFN_XProtocolRevision)(
    Display*		
);
typedef int(*PFN_XProtocolVersion)(
    Display*		
);
typedef int(*PFN_XPutBackEvent)(
    Display*		,
    XEvent*		
);
typedef int(*PFN_XPutImage)(
    Display*		,
    Drawable		,
    GC			,
    XImage*		,
    int			,
    int			,
    int			,
    int			,
    unsigned int	,
    unsigned int	
);
typedef int(*PFN_XQLength)(
    Display*		
);
typedef Status(*PFN_XQueryBestCursor)(
    Display*		,
    Drawable		,
    unsigned int        ,
    unsigned int	,
    unsigned int*	,
    unsigned int*	
);
typedef Status(*PFN_XQueryBestSize)(
    Display*		,
    int			,
    Drawable		,
    unsigned int	,
    unsigned int	,
    unsigned int*	,
    unsigned int*	
);
typedef Status(*PFN_XQueryBestStipple)(
    Display*		,
    Drawable		,
    unsigned int	,
    unsigned int	,
    unsigned int*	,
    unsigned int*	
);
typedef Status(*PFN_XQueryBestTile)(
    Display*		,
    Drawable		,
    unsigned int	,
    unsigned int	,
    unsigned int*	,
    unsigned int*	
);
typedef int(*PFN_XQueryColor)(
    Display*		,
    Colormap		,
    XColor*		
);
typedef int(*PFN_XQueryColors)(
    Display*		,
    Colormap		,
    XColor*		,
    int			
);
typedef Bool(*PFN_XQueryExtension)(
    Display*		,
    _Xconst char*	,
    int*		,
    int*		,
    int*		
);
typedef int(*PFN_XQueryKeymap)(
    Display*		,
    char [32]		
);
typedef Bool(*PFN_XQueryPointer)(
    Display*		,
    Window		,
    Window*		,
    Window*		,
    int*		,
    int*		,
    int*		,
    int*		,
    unsigned int*       
);
typedef int(*PFN_XQueryTextExtents)(
    Display*		,
    XID			,
    _Xconst char*	,
    int			,
    int*		,
    int*		,
    int*		,
    XCharStruct*	
);
typedef int(*PFN_XQueryTextExtents16)(
    Display*		,
    XID			,
    _Xconst XChar2b*	,
    int			,
    int*		,
    int*		,
    int*		,
    XCharStruct*	
);
typedef Status(*PFN_XQueryTree)(
    Display*		,
    Window		,
    Window*		,
    Window*		,
    Window**		,
    unsigned int*	
);
typedef int(*PFN_XRaiseWindow)(
    Display*		,
    Window		
);
typedef int(*PFN_XReadBitmapFile)(
    Display*		,
    Drawable 		,
    _Xconst char*	,
    unsigned int*	,
    unsigned int*	,
    Pixmap*		,
    int*		,
    int*		
);
typedef int(*PFN_XReadBitmapFileData)(
    _Xconst char*	,
    unsigned int*	,
    unsigned int*	,
    unsigned char**	,
    int*		,
    int*		
);
typedef int(*PFN_XRebindKeysym)(
    Display*		,
    KeySym		,
    KeySym*		,
    int			,
    _Xconst unsigned char*	,
    int			
);
typedef int(*PFN_XRecolorCursor)(
    Display*		,
    Cursor		,
    XColor*		,
    XColor*		
);
typedef int(*PFN_XRefreshKeyboardMapping)(
    XMappingEvent*	
);
typedef int(*PFN_XRemoveFromSaveSet)(
    Display*		,
    Window		
);
typedef int(*PFN_XRemoveHost)(
    Display*		,
    XHostAddress*	
);
typedef int(*PFN_XRemoveHosts)(
    Display*		,
    XHostAddress*	,
    int			
);
typedef int(*PFN_XReparentWindow)(
    Display*		,
    Window		,
    Window		,
    int			,
    int			
);
typedef int(*PFN_XResetScreenSaver)(
    Display*		
);
typedef int(*PFN_XResizeWindow)(
    Display*		,
    Window		,
    unsigned int	,
    unsigned int	
);
typedef int(*PFN_XRestackWindows)(
    Display*		,
    Window*		,
    int			
);
typedef int(*PFN_XRotateBuffers)(
    Display*		,
    int			
);
typedef int(*PFN_XRotateWindowProperties)(
    Display*		,
    Window		,
    Atom*		,
    int			,
    int			
);
typedef int(*PFN_XScreenCount)(
    Display*		
);
typedef int(*PFN_XSelectInput)(
    Display*		,
    Window		,
    long		
);
typedef Status(*PFN_XSendEvent)(
    Display*		,
    Window		,
    Bool		,
    long		,
    XEvent*		
);
typedef int(*PFN_XSetAccessControl)(
    Display*		,
    int			
);
typedef int(*PFN_XSetArcMode)(
    Display*		,
    GC			,
    int			
);
typedef int(*PFN_XSetBackground)(
    Display*		,
    GC			,
    unsigned long	
);
typedef int(*PFN_XSetClipMask)(
    Display*		,
    GC			,
    Pixmap		
);
typedef int(*PFN_XSetClipOrigin)(
    Display*		,
    GC			,
    int			,
    int			
);
typedef int(*PFN_XSetClipRectangles)(
    Display*		,
    GC			,
    int			,
    int			,
    XRectangle*		,
    int			,
    int			
);
typedef int(*PFN_XSetCloseDownMode)(
    Display*		,
    int			
);
typedef int(*PFN_XSetCommand)(
    Display*		,
    Window		,
    char**		,
    int			
);
typedef int(*PFN_XSetDashes)(
    Display*		,
    GC			,
    int			,
    _Xconst char*	,
    int			
);
typedef int(*PFN_XSetFillRule)(
    Display*		,
    GC			,
    int			
);
typedef int(*PFN_XSetFillStyle)(
    Display*		,
    GC			,
    int			
);
typedef int(*PFN_XSetFont)(
    Display*		,
    GC			,
    Font		
);
typedef int(*PFN_XSetFontPath)(
    Display*		,
    char**		,
    int			
);
typedef int(*PFN_XSetForeground)(
    Display*		,
    GC			,
    unsigned long	
);
typedef int(*PFN_XSetFunction)(
    Display*		,
    GC			,
    int			
);
typedef int(*PFN_XSetGraphicsExposures)(
    Display*		,
    GC			,
    Bool		
);
typedef int(*PFN_XSetIconName)(
    Display*		,
    Window		,
    _Xconst char*	
);
typedef int(*PFN_XSetInputFocus)(
    Display*		,
    Window		,
    int			,
    Time		
);
typedef int(*PFN_XSetLineAttributes)(
    Display*		,
    GC			,
    unsigned int	,
    int			,
    int			,
    int			
);
typedef int(*PFN_XSetModifierMapping)(
    Display*		,
    XModifierKeymap*	
);
typedef int(*PFN_XSetPlaneMask)(
    Display*		,
    GC			,
    unsigned long	
);
typedef int(*PFN_XSetPointerMapping)(
    Display*		,
    _Xconst unsigned char*	,
    int			
);
typedef int(*PFN_XSetScreenSaver)(
    Display*		,
    int			,
    int			,
    int			,
    int			
);
typedef int(*PFN_XSetSelectionOwner)(
    Display*		,
    Atom	        ,
    Window		,
    Time		
);
typedef int(*PFN_XSetState)(
    Display*		,
    GC			,
    unsigned long 	,
    unsigned long	,
    int			,
    unsigned long	
);
typedef int(*PFN_XSetStipple)(
    Display*		,
    GC			,
    Pixmap		
);
typedef int(*PFN_XSetSubwindowMode)(
    Display*		,
    GC			,
    int			
);
typedef int(*PFN_XSetTSOrigin)(
    Display*		,
    GC			,
    int			,
    int			
);
typedef int(*PFN_XSetTile)(
    Display*		,
    GC			,
    Pixmap		
);
typedef int(*PFN_XSetWindowBackground)(
    Display*		,
    Window		,
    unsigned long	
);
typedef int(*PFN_XSetWindowBackgroundPixmap)(
    Display*		,
    Window		,
    Pixmap		
);
typedef int(*PFN_XSetWindowBorder)(
    Display*		,
    Window		,
    unsigned long	
);
typedef int(*PFN_XSetWindowBorderPixmap)(
    Display*		,
    Window		,
    Pixmap		
);
typedef int(*PFN_XSetWindowBorderWidth)(
    Display*		,
    Window		,
    unsigned int	
);
typedef int(*PFN_XSetWindowColormap)(
    Display*		,
    Window		,
    Colormap		
);
typedef int(*PFN_XStoreBuffer)(
    Display*		,
    _Xconst char*	,
    int			,
    int			
);
typedef int(*PFN_XStoreBytes)(
    Display*		,
    _Xconst char*	,
    int			
);
typedef int(*PFN_XStoreColor)(
    Display*		,
    Colormap		,
    XColor*		
);
typedef int(*PFN_XStoreColors)(
    Display*		,
    Colormap		,
    XColor*		,
    int			
);
typedef int(*PFN_XStoreName)(
    Display*		,
    Window		,
    _Xconst char*	
);
typedef int(*PFN_XStoreNamedColor)(
    Display*		,
    Colormap		,
    _Xconst char*	,
    unsigned long	,
    int			
);
typedef int(*PFN_XSync)(
    Display*		,
    Bool		
);
typedef int(*PFN_XTextExtents)(
    XFontStruct*	,
    _Xconst char*	,
    int			,
    int*		,
    int*		,
    int*		,
    XCharStruct*	
);
typedef int(*PFN_XTextExtents16)(
    XFontStruct*	,
    _Xconst XChar2b*	,
    int			,
    int*		,
    int*		,
    int*		,
    XCharStruct*	
);
typedef int(*PFN_XTextWidth)(
    XFontStruct*	,
    _Xconst char*	,
    int			
);
typedef int(*PFN_XTextWidth16)(
    XFontStruct*	,
    _Xconst XChar2b*	,
    int			
);
typedef Bool(*PFN_XTranslateCoordinates)(
    Display*		,
    Window		,
    Window		,
    int			,
    int			,
    int*		,
    int*		,
    Window*		
);
typedef int(*PFN_XUndefineCursor)(
    Display*		,
    Window		
);
typedef int(*PFN_XUngrabButton)(
    Display*		,
    unsigned int	,
    unsigned int	,
    Window		
);
typedef int(*PFN_XUngrabKey)(
    Display*		,
    int			,
    unsigned int	,
    Window		
);
typedef int(*PFN_XUngrabKeyboard)(
    Display*		,
    Time		
);
typedef int(*PFN_XUngrabPointer)(
    Display*		,
    Time		
);
typedef int(*PFN_XUngrabServer)(
    Display*		
);
typedef int(*PFN_XUninstallColormap)(
    Display*		,
    Colormap		
);
typedef int(*PFN_XUnloadFont)(
    Display*		,
    Font		
);
typedef int(*PFN_XUnmapSubwindows)(
    Display*		,
    Window		
);
typedef int(*PFN_XUnmapWindow)(
    Display*		,
    Window		
);
typedef int(*PFN_XVendorRelease)(
    Display*		
);
typedef int(*PFN_XWarpPointer)(
    Display*		,
    Window		,
    Window		,
    int			,
    int			,
    unsigned int	,
    unsigned int	,
    int			,
    int			
);
typedef int(*PFN_XWidthMMOfScreen)(
    Screen*		
);
typedef int(*PFN_XWidthOfScreen)(
    Screen*		
);
typedef int(*PFN_XWindowEvent)(
    Display*		,
    Window		,
    long		,
    XEvent*		
);
typedef int(*PFN_XWriteBitmapFile)(
    Display*		,
    _Xconst char*	,
    Pixmap		,
    unsigned int	,
    unsigned int	,
    int			,
    int			
);
typedef Bool(*PFN_XSupportsLocale)(void);
typedef char*(*PFN_XSetLocaleModifiers)(
    const char*		
);
typedef XOM(*PFN_XOpenOM)(
    Display*			,
    struct _XrmHashBucketRec*	,
    _Xconst char*		,
    _Xconst char*		
);
typedef Status(*PFN_XCloseOM)(
    XOM			
);
typedef Display*(*PFN_XDisplayOfOM)(
    XOM			
);
typedef char*(*PFN_XLocaleOfOM)(
    XOM			
);
typedef void(*PFN_XDestroyOC)(
    XOC			
);
typedef XOM(*PFN_XOMOfOC)(
    XOC			
);
typedef XFontSet(*PFN_XCreateFontSet)(
    Display*		,
    _Xconst char*	,
    char***		,
    int*		,
    char**		
);
typedef void(*PFN_XFreeFontSet)(
    Display*		,
    XFontSet		
);
typedef int(*PFN_XFontsOfFontSet)(
    XFontSet		,
    XFontStruct***	,
    char***		
);
typedef char*(*PFN_XBaseFontNameListOfFontSet)(
    XFontSet		
);
typedef char*(*PFN_XLocaleOfFontSet)(
    XFontSet		
);
typedef Bool(*PFN_XContextDependentDrawing)(
    XFontSet		
);
typedef Bool(*PFN_XDirectionalDependentDrawing)(
    XFontSet		
);
typedef Bool(*PFN_XContextualDrawing)(
    XFontSet		
);
typedef XFontSetExtents*(*PFN_XExtentsOfFontSet)(
    XFontSet		
);
typedef int(*PFN_XmbTextEscapement)(
    XFontSet		,
    _Xconst char*	,
    int			
);
typedef int(*PFN_XwcTextEscapement)(
    XFontSet		,
    _Xconst wchar_t*	,
    int			
);
typedef int(*PFN_Xutf8TextEscapement)(
    XFontSet		,
    _Xconst char*	,
    int			
);
typedef int(*PFN_XmbTextExtents)(
    XFontSet		,
    _Xconst char*	,
    int			,
    XRectangle*		,
    XRectangle*		
);
typedef int(*PFN_XwcTextExtents)(
    XFontSet		,
    _Xconst wchar_t*	,
    int			,
    XRectangle*		,
    XRectangle*		
);
typedef int(*PFN_Xutf8TextExtents)(
    XFontSet		,
    _Xconst char*	,
    int			,
    XRectangle*		,
    XRectangle*		
);
typedef Status(*PFN_XmbTextPerCharExtents)(
    XFontSet		,
    _Xconst char*	,
    int			,
    XRectangle*		,
    XRectangle*		,
    int			,
    int*		,
    XRectangle*		,
    XRectangle*		
);
typedef Status(*PFN_XwcTextPerCharExtents)(
    XFontSet		,
    _Xconst wchar_t*	,
    int			,
    XRectangle*		,
    XRectangle*		,
    int			,
    int*		,
    XRectangle*		,
    XRectangle*		
);
typedef Status(*PFN_Xutf8TextPerCharExtents)(
    XFontSet		,
    _Xconst char*	,
    int			,
    XRectangle*		,
    XRectangle*		,
    int			,
    int*		,
    XRectangle*		,
    XRectangle*		
);
typedef void(*PFN_XmbDrawText)(
    Display*		,
    Drawable		,
    GC			,
    int			,
    int			,
    XmbTextItem*	,
    int			
);
typedef void(*PFN_XwcDrawText)(
    Display*		,
    Drawable		,
    GC			,
    int			,
    int			,
    XwcTextItem*	,
    int			
);
typedef void(*PFN_Xutf8DrawText)(
    Display*		,
    Drawable		,
    GC			,
    int			,
    int			,
    XmbTextItem*	,
    int			
);
typedef void(*PFN_XmbDrawString)(
    Display*		,
    Drawable		,
    XFontSet		,
    GC			,
    int			,
    int			,
    _Xconst char*	,
    int			
);
typedef void(*PFN_XwcDrawString)(
    Display*		,
    Drawable		,
    XFontSet		,
    GC			,
    int			,
    int			,
    _Xconst wchar_t*	,
    int			
);
typedef void(*PFN_Xutf8DrawString)(
    Display*		,
    Drawable		,
    XFontSet		,
    GC			,
    int			,
    int			,
    _Xconst char*	,
    int			
);
typedef void(*PFN_XmbDrawImageString)(
    Display*		,
    Drawable		,
    XFontSet		,
    GC			,
    int			,
    int			,
    _Xconst char*	,
    int			
);
typedef void(*PFN_XwcDrawImageString)(
    Display*		,
    Drawable		,
    XFontSet		,
    GC			,
    int			,
    int			,
    _Xconst wchar_t*	,
    int			
);
typedef void(*PFN_Xutf8DrawImageString)(
    Display*		,
    Drawable		,
    XFontSet		,
    GC			,
    int			,
    int			,
    _Xconst char*	,
    int			
);
typedef XIM(*PFN_XOpenIM)(
    Display*			,
    struct _XrmHashBucketRec*	,
    char*			,
    char*			
);
typedef Status(*PFN_XCloseIM)(
    XIM 
);
typedef Display*(*PFN_XDisplayOfIM)(
    XIM 
);
typedef char*(*PFN_XLocaleOfIM)(
    XIM 
);
typedef void(*PFN_XDestroyIC)(
    XIC 
);
typedef void(*PFN_XSetICFocus)(
    XIC 
);
typedef void(*PFN_XUnsetICFocus)(
    XIC 
);
typedef wchar_t*(*PFN_XwcResetIC)(
    XIC 
);
typedef char*(*PFN_XmbResetIC)(
    XIC 
);
typedef char*(*PFN_Xutf8ResetIC)(
    XIC 
);
typedef XIM(*PFN_XIMOfIC)(
    XIC 
);
typedef Bool(*PFN_XFilterEvent)(
    XEvent*	,
    Window	
);
typedef int(*PFN_XmbLookupString)(
    XIC			,
    XKeyPressedEvent*	,
    char*		,
    int			,
    KeySym*		,
    Status*		
);
typedef int(*PFN_XwcLookupString)(
    XIC			,
    XKeyPressedEvent*	,
    wchar_t*		,
    int			,
    KeySym*		,
    Status*		
);
typedef int(*PFN_Xutf8LookupString)(
    XIC			,
    XKeyPressedEvent*	,
    char*		,
    int			,
    KeySym*		,
    Status*		
);
typedef Bool(*PFN_XRegisterIMInstantiateCallback)(
    Display*			,
    struct _XrmHashBucketRec*	,
    char*			,
    char*			,
    XIDProc			,
    XPointer			
);
typedef Bool(*PFN_XUnregisterIMInstantiateCallback)(
    Display*			,
    struct _XrmHashBucketRec*	,
    char*			,
    char*			,
    XIDProc			,
    XPointer			
);
typedef Status(*PFN_XInternalConnectionNumbers)(
    Display*			,
    int**			,
    int*			
);
typedef void(*PFN_XProcessInternalConnection)(
    Display*			,
    int				
);
typedef Status(*PFN_XAddConnectionWatch)(
    Display*			,
    XConnectionWatchProc	,
    XPointer			
);
typedef void(*PFN_XRemoveConnectionWatch)(
    Display*			,
    XConnectionWatchProc	,
    XPointer			
);
typedef void(*PFN_XSetAuthorization)(
    char *			,
    int				,
    char *			,
    int				
);
typedef int(*PFN__Xmbtowc)(
    wchar_t *			,
    char *			,
    int				
);
typedef int(*PFN__Xwctomb)(
    char *			,
    wchar_t			
);
typedef Bool(*PFN_XGetEventData)(
    Display*			,
    XGenericEventCookie*	
);
typedef void(*PFN_XFreeEventData)(
    Display*			,
    XGenericEventCookie*	
);
PFN__Xmblen src__Xmblen;
PFN_XLoadQueryFont src_XLoadQueryFont;
PFN_XQueryFont src_XQueryFont;
PFN_XGetMotionEvents src_XGetMotionEvents;
PFN_XDeleteModifiermapEntry src_XDeleteModifiermapEntry;
PFN_XGetModifierMapping src_XGetModifierMapping;
PFN_XInsertModifiermapEntry src_XInsertModifiermapEntry;
PFN_XNewModifiermap src_XNewModifiermap;
PFN_XCreateImage src_XCreateImage;
PFN_XInitImage src_XInitImage;
PFN_XGetImage src_XGetImage;
PFN_XGetSubImage src_XGetSubImage;
PFN_XOpenDisplay src_XOpenDisplay;
PFN_XrmInitialize src_XrmInitialize;
PFN_XFetchBytes src_XFetchBytes;
PFN_XFetchBuffer src_XFetchBuffer;
PFN_XGetAtomName src_XGetAtomName;
PFN_XGetAtomNames src_XGetAtomNames;
PFN_XGetDefault src_XGetDefault;
PFN_XDisplayName src_XDisplayName;
PFN_XKeysymToString src_XKeysymToString;
PFN_XInternAtom src_XInternAtom;
PFN_XInternAtoms src_XInternAtoms;
PFN_XCopyColormapAndFree src_XCopyColormapAndFree;
PFN_XCreateColormap src_XCreateColormap;
PFN_XCreatePixmapCursor src_XCreatePixmapCursor;
PFN_XCreateGlyphCursor src_XCreateGlyphCursor;
PFN_XCreateFontCursor src_XCreateFontCursor;
PFN_XLoadFont src_XLoadFont;
PFN_XCreateGC src_XCreateGC;
PFN_XGContextFromGC src_XGContextFromGC;
PFN_XFlushGC src_XFlushGC;
PFN_XCreatePixmap src_XCreatePixmap;
PFN_XCreateBitmapFromData src_XCreateBitmapFromData;
PFN_XCreatePixmapFromBitmapData src_XCreatePixmapFromBitmapData;
PFN_XCreateSimpleWindow src_XCreateSimpleWindow;
PFN_XGetSelectionOwner src_XGetSelectionOwner;
PFN_XCreateWindow src_XCreateWindow;
PFN_XListInstalledColormaps src_XListInstalledColormaps;
PFN_XListFonts src_XListFonts;
PFN_XListFontsWithInfo src_XListFontsWithInfo;
PFN_XGetFontPath src_XGetFontPath;
PFN_XListExtensions src_XListExtensions;
PFN_XListProperties src_XListProperties;
PFN_XListHosts src_XListHosts;
PFN_XKeycodeToKeysym src_XKeycodeToKeysym;
PFN_XLookupKeysym src_XLookupKeysym;
PFN_XGetKeyboardMapping src_XGetKeyboardMapping;
PFN_XStringToKeysym src_XStringToKeysym;
PFN_XMaxRequestSize src_XMaxRequestSize;
PFN_XExtendedMaxRequestSize src_XExtendedMaxRequestSize;
PFN_XResourceManagerString src_XResourceManagerString;
PFN_XScreenResourceString src_XScreenResourceString;
PFN_XDisplayMotionBufferSize src_XDisplayMotionBufferSize;
PFN_XVisualIDFromVisual src_XVisualIDFromVisual;
PFN_XInitThreads src_XInitThreads;
PFN_XLockDisplay src_XLockDisplay;
PFN_XUnlockDisplay src_XUnlockDisplay;
PFN_XInitExtension src_XInitExtension;
PFN_XAddExtension src_XAddExtension;
PFN_XFindOnExtensionList src_XFindOnExtensionList;
PFN_XEHeadOfExtensionList src_XEHeadOfExtensionList;
PFN_XRootWindow src_XRootWindow;
PFN_XDefaultRootWindow src_XDefaultRootWindow;
PFN_XRootWindowOfScreen src_XRootWindowOfScreen;
PFN_XDefaultVisual src_XDefaultVisual;
PFN_XDefaultVisualOfScreen src_XDefaultVisualOfScreen;
PFN_XDefaultGC src_XDefaultGC;
PFN_XDefaultGCOfScreen src_XDefaultGCOfScreen;
PFN_XBlackPixel src_XBlackPixel;
PFN_XWhitePixel src_XWhitePixel;
PFN_XAllPlanes src_XAllPlanes;
PFN_XBlackPixelOfScreen src_XBlackPixelOfScreen;
PFN_XWhitePixelOfScreen src_XWhitePixelOfScreen;
PFN_XNextRequest src_XNextRequest;
PFN_XLastKnownRequestProcessed src_XLastKnownRequestProcessed;
PFN_XServerVendor src_XServerVendor;
PFN_XDisplayString src_XDisplayString;
PFN_XDefaultColormap src_XDefaultColormap;
PFN_XDefaultColormapOfScreen src_XDefaultColormapOfScreen;
PFN_XDisplayOfScreen src_XDisplayOfScreen;
PFN_XScreenOfDisplay src_XScreenOfDisplay;
PFN_XDefaultScreenOfDisplay src_XDefaultScreenOfDisplay;
PFN_XEventMaskOfScreen src_XEventMaskOfScreen;
PFN_XScreenNumberOfScreen src_XScreenNumberOfScreen;
PFN_XSetErrorHandler src_XSetErrorHandler;
PFN_XSetIOErrorHandler src_XSetIOErrorHandler;
PFN_XSetIOErrorExitHandler src_XSetIOErrorExitHandler;
PFN_XListPixmapFormats src_XListPixmapFormats;
PFN_XListDepths src_XListDepths;
PFN_XReconfigureWMWindow src_XReconfigureWMWindow;
PFN_XGetWMProtocols src_XGetWMProtocols;
PFN_XSetWMProtocols src_XSetWMProtocols;
PFN_XIconifyWindow src_XIconifyWindow;
PFN_XWithdrawWindow src_XWithdrawWindow;
PFN_XGetCommand src_XGetCommand;
PFN_XGetWMColormapWindows src_XGetWMColormapWindows;
PFN_XSetWMColormapWindows src_XSetWMColormapWindows;
PFN_XFreeStringList src_XFreeStringList;
PFN_XSetTransientForHint src_XSetTransientForHint;
PFN_XActivateScreenSaver src_XActivateScreenSaver;
PFN_XAddHost src_XAddHost;
PFN_XAddHosts src_XAddHosts;
PFN_XAddToExtensionList src_XAddToExtensionList;
PFN_XAddToSaveSet src_XAddToSaveSet;
PFN_XAllocColor src_XAllocColor;
PFN_XAllocColorCells src_XAllocColorCells;
PFN_XAllocColorPlanes src_XAllocColorPlanes;
PFN_XAllocNamedColor src_XAllocNamedColor;
PFN_XAllowEvents src_XAllowEvents;
PFN_XAutoRepeatOff src_XAutoRepeatOff;
PFN_XAutoRepeatOn src_XAutoRepeatOn;
PFN_XBell src_XBell;
PFN_XBitmapBitOrder src_XBitmapBitOrder;
PFN_XBitmapPad src_XBitmapPad;
PFN_XBitmapUnit src_XBitmapUnit;
PFN_XCellsOfScreen src_XCellsOfScreen;
PFN_XChangeActivePointerGrab src_XChangeActivePointerGrab;
PFN_XChangeGC src_XChangeGC;
PFN_XChangeKeyboardControl src_XChangeKeyboardControl;
PFN_XChangeKeyboardMapping src_XChangeKeyboardMapping;
PFN_XChangePointerControl src_XChangePointerControl;
PFN_XChangeProperty src_XChangeProperty;
PFN_XChangeSaveSet src_XChangeSaveSet;
PFN_XChangeWindowAttributes src_XChangeWindowAttributes;
PFN_XCheckMaskEvent src_XCheckMaskEvent;
PFN_XCheckTypedEvent src_XCheckTypedEvent;
PFN_XCheckTypedWindowEvent src_XCheckTypedWindowEvent;
PFN_XCheckWindowEvent src_XCheckWindowEvent;
PFN_XCirculateSubwindows src_XCirculateSubwindows;
PFN_XCirculateSubwindowsDown src_XCirculateSubwindowsDown;
PFN_XCirculateSubwindowsUp src_XCirculateSubwindowsUp;
PFN_XClearArea src_XClearArea;
PFN_XClearWindow src_XClearWindow;
PFN_XCloseDisplay src_XCloseDisplay;
PFN_XConfigureWindow src_XConfigureWindow;
PFN_XConnectionNumber src_XConnectionNumber;
PFN_XConvertSelection src_XConvertSelection;
PFN_XCopyArea src_XCopyArea;
PFN_XCopyGC src_XCopyGC;
PFN_XCopyPlane src_XCopyPlane;
PFN_XDefaultDepth src_XDefaultDepth;
PFN_XDefaultDepthOfScreen src_XDefaultDepthOfScreen;
PFN_XDefaultScreen src_XDefaultScreen;
PFN_XDefineCursor src_XDefineCursor;
PFN_XDeleteProperty src_XDeleteProperty;
PFN_XDestroyWindow src_XDestroyWindow;
PFN_XDestroySubwindows src_XDestroySubwindows;
PFN_XDoesBackingStore src_XDoesBackingStore;
PFN_XDoesSaveUnders src_XDoesSaveUnders;
PFN_XDisableAccessControl src_XDisableAccessControl;
PFN_XDisplayCells src_XDisplayCells;
PFN_XDisplayHeight src_XDisplayHeight;
PFN_XDisplayHeightMM src_XDisplayHeightMM;
PFN_XDisplayKeycodes src_XDisplayKeycodes;
PFN_XDisplayPlanes src_XDisplayPlanes;
PFN_XDisplayWidth src_XDisplayWidth;
PFN_XDisplayWidthMM src_XDisplayWidthMM;
PFN_XDrawArc src_XDrawArc;
PFN_XDrawArcs src_XDrawArcs;
PFN_XDrawImageString src_XDrawImageString;
PFN_XDrawImageString16 src_XDrawImageString16;
PFN_XDrawLine src_XDrawLine;
PFN_XDrawLines src_XDrawLines;
PFN_XDrawPoint src_XDrawPoint;
PFN_XDrawPoints src_XDrawPoints;
PFN_XDrawRectangle src_XDrawRectangle;
PFN_XDrawRectangles src_XDrawRectangles;
PFN_XDrawSegments src_XDrawSegments;
PFN_XDrawString src_XDrawString;
PFN_XDrawString16 src_XDrawString16;
PFN_XDrawText src_XDrawText;
PFN_XDrawText16 src_XDrawText16;
PFN_XEnableAccessControl src_XEnableAccessControl;
PFN_XEventsQueued src_XEventsQueued;
PFN_XFetchName src_XFetchName;
PFN_XFillArc src_XFillArc;
PFN_XFillArcs src_XFillArcs;
PFN_XFillPolygon src_XFillPolygon;
PFN_XFillRectangle src_XFillRectangle;
PFN_XFillRectangles src_XFillRectangles;
PFN_XFlush src_XFlush;
PFN_XForceScreenSaver src_XForceScreenSaver;
PFN_XFree src_XFree;
PFN_XFreeColormap src_XFreeColormap;
PFN_XFreeColors src_XFreeColors;
PFN_XFreeCursor src_XFreeCursor;
PFN_XFreeExtensionList src_XFreeExtensionList;
PFN_XFreeFont src_XFreeFont;
PFN_XFreeFontInfo src_XFreeFontInfo;
PFN_XFreeFontNames src_XFreeFontNames;
PFN_XFreeFontPath src_XFreeFontPath;
PFN_XFreeGC src_XFreeGC;
PFN_XFreeModifiermap src_XFreeModifiermap;
PFN_XFreePixmap src_XFreePixmap;
PFN_XGeometry src_XGeometry;
PFN_XGetErrorDatabaseText src_XGetErrorDatabaseText;
PFN_XGetErrorText src_XGetErrorText;
PFN_XGetFontProperty src_XGetFontProperty;
PFN_XGetGCValues src_XGetGCValues;
PFN_XGetGeometry src_XGetGeometry;
PFN_XGetIconName src_XGetIconName;
PFN_XGetInputFocus src_XGetInputFocus;
PFN_XGetKeyboardControl src_XGetKeyboardControl;
PFN_XGetPointerControl src_XGetPointerControl;
PFN_XGetPointerMapping src_XGetPointerMapping;
PFN_XGetScreenSaver src_XGetScreenSaver;
PFN_XGetTransientForHint src_XGetTransientForHint;
PFN_XGetWindowProperty src_XGetWindowProperty;
PFN_XGetWindowAttributes src_XGetWindowAttributes;
PFN_XGrabButton src_XGrabButton;
PFN_XGrabKey src_XGrabKey;
PFN_XGrabKeyboard src_XGrabKeyboard;
PFN_XGrabPointer src_XGrabPointer;
PFN_XGrabServer src_XGrabServer;
PFN_XHeightMMOfScreen src_XHeightMMOfScreen;
PFN_XHeightOfScreen src_XHeightOfScreen;
PFN_XImageByteOrder src_XImageByteOrder;
PFN_XInstallColormap src_XInstallColormap;
PFN_XKeysymToKeycode src_XKeysymToKeycode;
PFN_XKillClient src_XKillClient;
PFN_XLookupColor src_XLookupColor;
PFN_XLowerWindow src_XLowerWindow;
PFN_XMapRaised src_XMapRaised;
PFN_XMapSubwindows src_XMapSubwindows;
PFN_XMapWindow src_XMapWindow;
PFN_XMaskEvent src_XMaskEvent;
PFN_XMaxCmapsOfScreen src_XMaxCmapsOfScreen;
PFN_XMinCmapsOfScreen src_XMinCmapsOfScreen;
PFN_XMoveResizeWindow src_XMoveResizeWindow;
PFN_XMoveWindow src_XMoveWindow;
PFN_XNextEvent src_XNextEvent;
PFN_XNoOp src_XNoOp;
PFN_XParseColor src_XParseColor;
PFN_XParseGeometry src_XParseGeometry;
PFN_XPeekEvent src_XPeekEvent;
PFN_XPending src_XPending;
PFN_XPlanesOfScreen src_XPlanesOfScreen;
PFN_XProtocolRevision src_XProtocolRevision;
PFN_XProtocolVersion src_XProtocolVersion;
PFN_XPutBackEvent src_XPutBackEvent;
PFN_XPutImage src_XPutImage;
PFN_XQLength src_XQLength;
PFN_XQueryBestCursor src_XQueryBestCursor;
PFN_XQueryBestSize src_XQueryBestSize;
PFN_XQueryBestStipple src_XQueryBestStipple;
PFN_XQueryBestTile src_XQueryBestTile;
PFN_XQueryColor src_XQueryColor;
PFN_XQueryColors src_XQueryColors;
PFN_XQueryExtension src_XQueryExtension;
PFN_XQueryKeymap src_XQueryKeymap;
PFN_XQueryPointer src_XQueryPointer;
PFN_XQueryTextExtents src_XQueryTextExtents;
PFN_XQueryTextExtents16 src_XQueryTextExtents16;
PFN_XQueryTree src_XQueryTree;
PFN_XRaiseWindow src_XRaiseWindow;
PFN_XReadBitmapFile src_XReadBitmapFile;
PFN_XReadBitmapFileData src_XReadBitmapFileData;
PFN_XRebindKeysym src_XRebindKeysym;
PFN_XRecolorCursor src_XRecolorCursor;
PFN_XRefreshKeyboardMapping src_XRefreshKeyboardMapping;
PFN_XRemoveFromSaveSet src_XRemoveFromSaveSet;
PFN_XRemoveHost src_XRemoveHost;
PFN_XRemoveHosts src_XRemoveHosts;
PFN_XReparentWindow src_XReparentWindow;
PFN_XResetScreenSaver src_XResetScreenSaver;
PFN_XResizeWindow src_XResizeWindow;
PFN_XRestackWindows src_XRestackWindows;
PFN_XRotateBuffers src_XRotateBuffers;
PFN_XRotateWindowProperties src_XRotateWindowProperties;
PFN_XScreenCount src_XScreenCount;
PFN_XSelectInput src_XSelectInput;
PFN_XSendEvent src_XSendEvent;
PFN_XSetAccessControl src_XSetAccessControl;
PFN_XSetArcMode src_XSetArcMode;
PFN_XSetBackground src_XSetBackground;
PFN_XSetClipMask src_XSetClipMask;
PFN_XSetClipOrigin src_XSetClipOrigin;
PFN_XSetClipRectangles src_XSetClipRectangles;
PFN_XSetCloseDownMode src_XSetCloseDownMode;
PFN_XSetCommand src_XSetCommand;
PFN_XSetDashes src_XSetDashes;
PFN_XSetFillRule src_XSetFillRule;
PFN_XSetFillStyle src_XSetFillStyle;
PFN_XSetFont src_XSetFont;
PFN_XSetFontPath src_XSetFontPath;
PFN_XSetForeground src_XSetForeground;
PFN_XSetFunction src_XSetFunction;
PFN_XSetGraphicsExposures src_XSetGraphicsExposures;
PFN_XSetIconName src_XSetIconName;
PFN_XSetInputFocus src_XSetInputFocus;
PFN_XSetLineAttributes src_XSetLineAttributes;
PFN_XSetModifierMapping src_XSetModifierMapping;
PFN_XSetPlaneMask src_XSetPlaneMask;
PFN_XSetPointerMapping src_XSetPointerMapping;
PFN_XSetScreenSaver src_XSetScreenSaver;
PFN_XSetSelectionOwner src_XSetSelectionOwner;
PFN_XSetState src_XSetState;
PFN_XSetStipple src_XSetStipple;
PFN_XSetSubwindowMode src_XSetSubwindowMode;
PFN_XSetTSOrigin src_XSetTSOrigin;
PFN_XSetTile src_XSetTile;
PFN_XSetWindowBackground src_XSetWindowBackground;
PFN_XSetWindowBackgroundPixmap src_XSetWindowBackgroundPixmap;
PFN_XSetWindowBorder src_XSetWindowBorder;
PFN_XSetWindowBorderPixmap src_XSetWindowBorderPixmap;
PFN_XSetWindowBorderWidth src_XSetWindowBorderWidth;
PFN_XSetWindowColormap src_XSetWindowColormap;
PFN_XStoreBuffer src_XStoreBuffer;
PFN_XStoreBytes src_XStoreBytes;
PFN_XStoreColor src_XStoreColor;
PFN_XStoreColors src_XStoreColors;
PFN_XStoreName src_XStoreName;
PFN_XStoreNamedColor src_XStoreNamedColor;
PFN_XSync src_XSync;
PFN_XTextExtents src_XTextExtents;
PFN_XTextExtents16 src_XTextExtents16;
PFN_XTextWidth src_XTextWidth;
PFN_XTextWidth16 src_XTextWidth16;
PFN_XTranslateCoordinates src_XTranslateCoordinates;
PFN_XUndefineCursor src_XUndefineCursor;
PFN_XUngrabButton src_XUngrabButton;
PFN_XUngrabKey src_XUngrabKey;
PFN_XUngrabKeyboard src_XUngrabKeyboard;
PFN_XUngrabPointer src_XUngrabPointer;
PFN_XUngrabServer src_XUngrabServer;
PFN_XUninstallColormap src_XUninstallColormap;
PFN_XUnloadFont src_XUnloadFont;
PFN_XUnmapSubwindows src_XUnmapSubwindows;
PFN_XUnmapWindow src_XUnmapWindow;
PFN_XVendorRelease src_XVendorRelease;
PFN_XWarpPointer src_XWarpPointer;
PFN_XWidthMMOfScreen src_XWidthMMOfScreen;
PFN_XWidthOfScreen src_XWidthOfScreen;
PFN_XWindowEvent src_XWindowEvent;
PFN_XWriteBitmapFile src_XWriteBitmapFile;
PFN_XSupportsLocale src_XSupportsLocale;
PFN_XSetLocaleModifiers src_XSetLocaleModifiers;
PFN_XOpenOM src_XOpenOM;
PFN_XCloseOM src_XCloseOM;
PFN_XDisplayOfOM src_XDisplayOfOM;
PFN_XLocaleOfOM src_XLocaleOfOM;
PFN_XDestroyOC src_XDestroyOC;
PFN_XOMOfOC src_XOMOfOC;
PFN_XCreateFontSet src_XCreateFontSet;
PFN_XFreeFontSet src_XFreeFontSet;
PFN_XFontsOfFontSet src_XFontsOfFontSet;
PFN_XBaseFontNameListOfFontSet src_XBaseFontNameListOfFontSet;
PFN_XLocaleOfFontSet src_XLocaleOfFontSet;
PFN_XContextDependentDrawing src_XContextDependentDrawing;
PFN_XDirectionalDependentDrawing src_XDirectionalDependentDrawing;
PFN_XContextualDrawing src_XContextualDrawing;
PFN_XExtentsOfFontSet src_XExtentsOfFontSet;
PFN_XmbTextEscapement src_XmbTextEscapement;
PFN_XwcTextEscapement src_XwcTextEscapement;
PFN_Xutf8TextEscapement src_Xutf8TextEscapement;
PFN_XmbTextExtents src_XmbTextExtents;
PFN_XwcTextExtents src_XwcTextExtents;
PFN_Xutf8TextExtents src_Xutf8TextExtents;
PFN_XmbTextPerCharExtents src_XmbTextPerCharExtents;
PFN_XwcTextPerCharExtents src_XwcTextPerCharExtents;
PFN_Xutf8TextPerCharExtents src_Xutf8TextPerCharExtents;
PFN_XmbDrawText src_XmbDrawText;
PFN_XwcDrawText src_XwcDrawText;
PFN_Xutf8DrawText src_Xutf8DrawText;
PFN_XmbDrawString src_XmbDrawString;
PFN_XwcDrawString src_XwcDrawString;
PFN_Xutf8DrawString src_Xutf8DrawString;
PFN_XmbDrawImageString src_XmbDrawImageString;
PFN_XwcDrawImageString src_XwcDrawImageString;
PFN_Xutf8DrawImageString src_Xutf8DrawImageString;
PFN_XOpenIM src_XOpenIM;
PFN_XCloseIM src_XCloseIM;
PFN_XDisplayOfIM src_XDisplayOfIM;
PFN_XLocaleOfIM src_XLocaleOfIM;
PFN_XDestroyIC src_XDestroyIC;
PFN_XSetICFocus src_XSetICFocus;
PFN_XUnsetICFocus src_XUnsetICFocus;
PFN_XwcResetIC src_XwcResetIC;
PFN_XmbResetIC src_XmbResetIC;
PFN_Xutf8ResetIC src_Xutf8ResetIC;
PFN_XIMOfIC src_XIMOfIC;
PFN_XFilterEvent src_XFilterEvent;
PFN_XmbLookupString src_XmbLookupString;
PFN_XwcLookupString src_XwcLookupString;
PFN_Xutf8LookupString src_Xutf8LookupString;
PFN_XRegisterIMInstantiateCallback src_XRegisterIMInstantiateCallback;
PFN_XUnregisterIMInstantiateCallback src_XUnregisterIMInstantiateCallback;
PFN_XInternalConnectionNumbers src_XInternalConnectionNumbers;
PFN_XProcessInternalConnection src_XProcessInternalConnection;
PFN_XAddConnectionWatch src_XAddConnectionWatch;
PFN_XRemoveConnectionWatch src_XRemoveConnectionWatch;
PFN_XSetAuthorization src_XSetAuthorization;
PFN__Xmbtowc src__Xmbtowc;
PFN__Xwctomb src__Xwctomb;
PFN_XGetEventData src_XGetEventData;
PFN_XFreeEventData src_XFreeEventData;
#define _Xmblen src__Xmblen
#define XLoadQueryFont src_XLoadQueryFont
#define XQueryFont src_XQueryFont
#define XGetMotionEvents src_XGetMotionEvents
#define XDeleteModifiermapEntry src_XDeleteModifiermapEntry
#define XGetModifierMapping src_XGetModifierMapping
#define XInsertModifiermapEntry src_XInsertModifiermapEntry
#define XNewModifiermap src_XNewModifiermap
#define XCreateImage src_XCreateImage
#define XInitImage src_XInitImage
#define XGetImage src_XGetImage
#define XGetSubImage src_XGetSubImage
#define XOpenDisplay src_XOpenDisplay
#define XrmInitialize src_XrmInitialize
#define XFetchBytes src_XFetchBytes
#define XFetchBuffer src_XFetchBuffer
#define XGetAtomName src_XGetAtomName
#define XGetAtomNames src_XGetAtomNames
#define XGetDefault src_XGetDefault
#define XDisplayName src_XDisplayName
#define XKeysymToString src_XKeysymToString
#define XInternAtom src_XInternAtom
#define XInternAtoms src_XInternAtoms
#define XCopyColormapAndFree src_XCopyColormapAndFree
#define XCreateColormap src_XCreateColormap
#define XCreatePixmapCursor src_XCreatePixmapCursor
#define XCreateGlyphCursor src_XCreateGlyphCursor
#define XCreateFontCursor src_XCreateFontCursor
#define XLoadFont src_XLoadFont
#define XCreateGC src_XCreateGC
#define XGContextFromGC src_XGContextFromGC
#define XFlushGC src_XFlushGC
#define XCreatePixmap src_XCreatePixmap
#define XCreateBitmapFromData src_XCreateBitmapFromData
#define XCreatePixmapFromBitmapData src_XCreatePixmapFromBitmapData
#define XCreateSimpleWindow src_XCreateSimpleWindow
#define XGetSelectionOwner src_XGetSelectionOwner
#define XCreateWindow src_XCreateWindow
#define XListInstalledColormaps src_XListInstalledColormaps
#define XListFonts src_XListFonts
#define XListFontsWithInfo src_XListFontsWithInfo
#define XGetFontPath src_XGetFontPath
#define XListExtensions src_XListExtensions
#define XListProperties src_XListProperties
#define XListHosts src_XListHosts
#define XKeycodeToKeysym src_XKeycodeToKeysym
#define XLookupKeysym src_XLookupKeysym
#define XGetKeyboardMapping src_XGetKeyboardMapping
#define XStringToKeysym src_XStringToKeysym
#define XMaxRequestSize src_XMaxRequestSize
#define XExtendedMaxRequestSize src_XExtendedMaxRequestSize
#define XResourceManagerString src_XResourceManagerString
#define XScreenResourceString src_XScreenResourceString
#define XDisplayMotionBufferSize src_XDisplayMotionBufferSize
#define XVisualIDFromVisual src_XVisualIDFromVisual
#define XInitThreads src_XInitThreads
#define XLockDisplay src_XLockDisplay
#define XUnlockDisplay src_XUnlockDisplay
#define XInitExtension src_XInitExtension
#define XAddExtension src_XAddExtension
#define XFindOnExtensionList src_XFindOnExtensionList
#define XEHeadOfExtensionList src_XEHeadOfExtensionList
#define XRootWindow src_XRootWindow
#define XDefaultRootWindow src_XDefaultRootWindow
#define XRootWindowOfScreen src_XRootWindowOfScreen
#define XDefaultVisual src_XDefaultVisual
#define XDefaultVisualOfScreen src_XDefaultVisualOfScreen
#define XDefaultGC src_XDefaultGC
#define XDefaultGCOfScreen src_XDefaultGCOfScreen
#define XBlackPixel src_XBlackPixel
#define XWhitePixel src_XWhitePixel
#define XAllPlanes src_XAllPlanes
#define XBlackPixelOfScreen src_XBlackPixelOfScreen
#define XWhitePixelOfScreen src_XWhitePixelOfScreen
#define XNextRequest src_XNextRequest
#define XLastKnownRequestProcessed src_XLastKnownRequestProcessed
#define XServerVendor src_XServerVendor
#define XDisplayString src_XDisplayString
#define XDefaultColormap src_XDefaultColormap
#define XDefaultColormapOfScreen src_XDefaultColormapOfScreen
#define XDisplayOfScreen src_XDisplayOfScreen
#define XScreenOfDisplay src_XScreenOfDisplay
#define XDefaultScreenOfDisplay src_XDefaultScreenOfDisplay
#define XEventMaskOfScreen src_XEventMaskOfScreen
#define XScreenNumberOfScreen src_XScreenNumberOfScreen
#define XSetErrorHandler src_XSetErrorHandler
#define XSetIOErrorHandler src_XSetIOErrorHandler
#define XSetIOErrorExitHandler src_XSetIOErrorExitHandler
#define XListPixmapFormats src_XListPixmapFormats
#define XListDepths src_XListDepths
#define XReconfigureWMWindow src_XReconfigureWMWindow
#define XGetWMProtocols src_XGetWMProtocols
#define XSetWMProtocols src_XSetWMProtocols
#define XIconifyWindow src_XIconifyWindow
#define XWithdrawWindow src_XWithdrawWindow
#define XGetCommand src_XGetCommand
#define XGetWMColormapWindows src_XGetWMColormapWindows
#define XSetWMColormapWindows src_XSetWMColormapWindows
#define XFreeStringList src_XFreeStringList
#define XSetTransientForHint src_XSetTransientForHint
#define XActivateScreenSaver src_XActivateScreenSaver
#define XAddHost src_XAddHost
#define XAddHosts src_XAddHosts
#define XAddToExtensionList src_XAddToExtensionList
#define XAddToSaveSet src_XAddToSaveSet
#define XAllocColor src_XAllocColor
#define XAllocColorCells src_XAllocColorCells
#define XAllocColorPlanes src_XAllocColorPlanes
#define XAllocNamedColor src_XAllocNamedColor
#define XAllowEvents src_XAllowEvents
#define XAutoRepeatOff src_XAutoRepeatOff
#define XAutoRepeatOn src_XAutoRepeatOn
#define XBell src_XBell
#define XBitmapBitOrder src_XBitmapBitOrder
#define XBitmapPad src_XBitmapPad
#define XBitmapUnit src_XBitmapUnit
#define XCellsOfScreen src_XCellsOfScreen
#define XChangeActivePointerGrab src_XChangeActivePointerGrab
#define XChangeGC src_XChangeGC
#define XChangeKeyboardControl src_XChangeKeyboardControl
#define XChangeKeyboardMapping src_XChangeKeyboardMapping
#define XChangePointerControl src_XChangePointerControl
#define XChangeProperty src_XChangeProperty
#define XChangeSaveSet src_XChangeSaveSet
#define XChangeWindowAttributes src_XChangeWindowAttributes
#define XCheckMaskEvent src_XCheckMaskEvent
#define XCheckTypedEvent src_XCheckTypedEvent
#define XCheckTypedWindowEvent src_XCheckTypedWindowEvent
#define XCheckWindowEvent src_XCheckWindowEvent
#define XCirculateSubwindows src_XCirculateSubwindows
#define XCirculateSubwindowsDown src_XCirculateSubwindowsDown
#define XCirculateSubwindowsUp src_XCirculateSubwindowsUp
#define XClearArea src_XClearArea
#define XClearWindow src_XClearWindow
#define XCloseDisplay src_XCloseDisplay
#define XConfigureWindow src_XConfigureWindow
#define XConnectionNumber src_XConnectionNumber
#define XConvertSelection src_XConvertSelection
#define XCopyArea src_XCopyArea
#define XCopyGC src_XCopyGC
#define XCopyPlane src_XCopyPlane
#define XDefaultDepth src_XDefaultDepth
#define XDefaultDepthOfScreen src_XDefaultDepthOfScreen
#define XDefaultScreen src_XDefaultScreen
#define XDefineCursor src_XDefineCursor
#define XDeleteProperty src_XDeleteProperty
#define XDestroyWindow src_XDestroyWindow
#define XDestroySubwindows src_XDestroySubwindows
#define XDoesBackingStore src_XDoesBackingStore
#define XDoesSaveUnders src_XDoesSaveUnders
#define XDisableAccessControl src_XDisableAccessControl
#define XDisplayCells src_XDisplayCells
#define XDisplayHeight src_XDisplayHeight
#define XDisplayHeightMM src_XDisplayHeightMM
#define XDisplayKeycodes src_XDisplayKeycodes
#define XDisplayPlanes src_XDisplayPlanes
#define XDisplayWidth src_XDisplayWidth
#define XDisplayWidthMM src_XDisplayWidthMM
#define XDrawArc src_XDrawArc
#define XDrawArcs src_XDrawArcs
#define XDrawImageString src_XDrawImageString
#define XDrawImageString16 src_XDrawImageString16
#define XDrawLine src_XDrawLine
#define XDrawLines src_XDrawLines
#define XDrawPoint src_XDrawPoint
#define XDrawPoints src_XDrawPoints
#define XDrawRectangle src_XDrawRectangle
#define XDrawRectangles src_XDrawRectangles
#define XDrawSegments src_XDrawSegments
#define XDrawString src_XDrawString
#define XDrawString16 src_XDrawString16
#define XDrawText src_XDrawText
#define XDrawText16 src_XDrawText16
#define XEnableAccessControl src_XEnableAccessControl
#define XEventsQueued src_XEventsQueued
#define XFetchName src_XFetchName
#define XFillArc src_XFillArc
#define XFillArcs src_XFillArcs
#define XFillPolygon src_XFillPolygon
#define XFillRectangle src_XFillRectangle
#define XFillRectangles src_XFillRectangles
#define XFlush src_XFlush
#define XForceScreenSaver src_XForceScreenSaver
#define XFree src_XFree
#define XFreeColormap src_XFreeColormap
#define XFreeColors src_XFreeColors
#define XFreeCursor src_XFreeCursor
#define XFreeExtensionList src_XFreeExtensionList
#define XFreeFont src_XFreeFont
#define XFreeFontInfo src_XFreeFontInfo
#define XFreeFontNames src_XFreeFontNames
#define XFreeFontPath src_XFreeFontPath
#define XFreeGC src_XFreeGC
#define XFreeModifiermap src_XFreeModifiermap
#define XFreePixmap src_XFreePixmap
#define XGeometry src_XGeometry
#define XGetErrorDatabaseText src_XGetErrorDatabaseText
#define XGetErrorText src_XGetErrorText
#define XGetFontProperty src_XGetFontProperty
#define XGetGCValues src_XGetGCValues
#define XGetGeometry src_XGetGeometry
#define XGetIconName src_XGetIconName
#define XGetInputFocus src_XGetInputFocus
#define XGetKeyboardControl src_XGetKeyboardControl
#define XGetPointerControl src_XGetPointerControl
#define XGetPointerMapping src_XGetPointerMapping
#define XGetScreenSaver src_XGetScreenSaver
#define XGetTransientForHint src_XGetTransientForHint
#define XGetWindowProperty src_XGetWindowProperty
#define XGetWindowAttributes src_XGetWindowAttributes
#define XGrabButton src_XGrabButton
#define XGrabKey src_XGrabKey
#define XGrabKeyboard src_XGrabKeyboard
#define XGrabPointer src_XGrabPointer
#define XGrabServer src_XGrabServer
#define XHeightMMOfScreen src_XHeightMMOfScreen
#define XHeightOfScreen src_XHeightOfScreen
#define XImageByteOrder src_XImageByteOrder
#define XInstallColormap src_XInstallColormap
#define XKeysymToKeycode src_XKeysymToKeycode
#define XKillClient src_XKillClient
#define XLookupColor src_XLookupColor
#define XLowerWindow src_XLowerWindow
#define XMapRaised src_XMapRaised
#define XMapSubwindows src_XMapSubwindows
#define XMapWindow src_XMapWindow
#define XMaskEvent src_XMaskEvent
#define XMaxCmapsOfScreen src_XMaxCmapsOfScreen
#define XMinCmapsOfScreen src_XMinCmapsOfScreen
#define XMoveResizeWindow src_XMoveResizeWindow
#define XMoveWindow src_XMoveWindow
#define XNextEvent src_XNextEvent
#define XNoOp src_XNoOp
#define XParseColor src_XParseColor
#define XParseGeometry src_XParseGeometry
#define XPeekEvent src_XPeekEvent
#define XPending src_XPending
#define XPlanesOfScreen src_XPlanesOfScreen
#define XProtocolRevision src_XProtocolRevision
#define XProtocolVersion src_XProtocolVersion
#define XPutBackEvent src_XPutBackEvent
#define XPutImage src_XPutImage
#define XQLength src_XQLength
#define XQueryBestCursor src_XQueryBestCursor
#define XQueryBestSize src_XQueryBestSize
#define XQueryBestStipple src_XQueryBestStipple
#define XQueryBestTile src_XQueryBestTile
#define XQueryColor src_XQueryColor
#define XQueryColors src_XQueryColors
#define XQueryExtension src_XQueryExtension
#define XQueryKeymap src_XQueryKeymap
#define XQueryPointer src_XQueryPointer
#define XQueryTextExtents src_XQueryTextExtents
#define XQueryTextExtents16 src_XQueryTextExtents16
#define XQueryTree src_XQueryTree
#define XRaiseWindow src_XRaiseWindow
#define XReadBitmapFile src_XReadBitmapFile
#define XReadBitmapFileData src_XReadBitmapFileData
#define XRebindKeysym src_XRebindKeysym
#define XRecolorCursor src_XRecolorCursor
#define XRefreshKeyboardMapping src_XRefreshKeyboardMapping
#define XRemoveFromSaveSet src_XRemoveFromSaveSet
#define XRemoveHost src_XRemoveHost
#define XRemoveHosts src_XRemoveHosts
#define XReparentWindow src_XReparentWindow
#define XResetScreenSaver src_XResetScreenSaver
#define XResizeWindow src_XResizeWindow
#define XRestackWindows src_XRestackWindows
#define XRotateBuffers src_XRotateBuffers
#define XRotateWindowProperties src_XRotateWindowProperties
#define XScreenCount src_XScreenCount
#define XSelectInput src_XSelectInput
#define XSendEvent src_XSendEvent
#define XSetAccessControl src_XSetAccessControl
#define XSetArcMode src_XSetArcMode
#define XSetBackground src_XSetBackground
#define XSetClipMask src_XSetClipMask
#define XSetClipOrigin src_XSetClipOrigin
#define XSetClipRectangles src_XSetClipRectangles
#define XSetCloseDownMode src_XSetCloseDownMode
#define XSetCommand src_XSetCommand
#define XSetDashes src_XSetDashes
#define XSetFillRule src_XSetFillRule
#define XSetFillStyle src_XSetFillStyle
#define XSetFont src_XSetFont
#define XSetFontPath src_XSetFontPath
#define XSetForeground src_XSetForeground
#define XSetFunction src_XSetFunction
#define XSetGraphicsExposures src_XSetGraphicsExposures
#define XSetIconName src_XSetIconName
#define XSetInputFocus src_XSetInputFocus
#define XSetLineAttributes src_XSetLineAttributes
#define XSetModifierMapping src_XSetModifierMapping
#define XSetPlaneMask src_XSetPlaneMask
#define XSetPointerMapping src_XSetPointerMapping
#define XSetScreenSaver src_XSetScreenSaver
#define XSetSelectionOwner src_XSetSelectionOwner
#define XSetState src_XSetState
#define XSetStipple src_XSetStipple
#define XSetSubwindowMode src_XSetSubwindowMode
#define XSetTSOrigin src_XSetTSOrigin
#define XSetTile src_XSetTile
#define XSetWindowBackground src_XSetWindowBackground
#define XSetWindowBackgroundPixmap src_XSetWindowBackgroundPixmap
#define XSetWindowBorder src_XSetWindowBorder
#define XSetWindowBorderPixmap src_XSetWindowBorderPixmap
#define XSetWindowBorderWidth src_XSetWindowBorderWidth
#define XSetWindowColormap src_XSetWindowColormap
#define XStoreBuffer src_XStoreBuffer
#define XStoreBytes src_XStoreBytes
#define XStoreColor src_XStoreColor
#define XStoreColors src_XStoreColors
#define XStoreName src_XStoreName
#define XStoreNamedColor src_XStoreNamedColor
#define XSync src_XSync
#define XTextExtents src_XTextExtents
#define XTextExtents16 src_XTextExtents16
#define XTextWidth src_XTextWidth
#define XTextWidth16 src_XTextWidth16
#define XTranslateCoordinates src_XTranslateCoordinates
#define XUndefineCursor src_XUndefineCursor
#define XUngrabButton src_XUngrabButton
#define XUngrabKey src_XUngrabKey
#define XUngrabKeyboard src_XUngrabKeyboard
#define XUngrabPointer src_XUngrabPointer
#define XUngrabServer src_XUngrabServer
#define XUninstallColormap src_XUninstallColormap
#define XUnloadFont src_XUnloadFont
#define XUnmapSubwindows src_XUnmapSubwindows
#define XUnmapWindow src_XUnmapWindow
#define XVendorRelease src_XVendorRelease
#define XWarpPointer src_XWarpPointer
#define XWidthMMOfScreen src_XWidthMMOfScreen
#define XWidthOfScreen src_XWidthOfScreen
#define XWindowEvent src_XWindowEvent
#define XWriteBitmapFile src_XWriteBitmapFile
#define XSupportsLocale src_XSupportsLocale
#define XSetLocaleModifiers src_XSetLocaleModifiers
#define XOpenOM src_XOpenOM
#define XCloseOM src_XCloseOM
#define XDisplayOfOM src_XDisplayOfOM
#define XLocaleOfOM src_XLocaleOfOM
#define XDestroyOC src_XDestroyOC
#define XOMOfOC src_XOMOfOC
#define XCreateFontSet src_XCreateFontSet
#define XFreeFontSet src_XFreeFontSet
#define XFontsOfFontSet src_XFontsOfFontSet
#define XBaseFontNameListOfFontSet src_XBaseFontNameListOfFontSet
#define XLocaleOfFontSet src_XLocaleOfFontSet
#define XContextDependentDrawing src_XContextDependentDrawing
#define XDirectionalDependentDrawing src_XDirectionalDependentDrawing
#define XContextualDrawing src_XContextualDrawing
#define XExtentsOfFontSet src_XExtentsOfFontSet
#define XmbTextEscapement src_XmbTextEscapement
#define XwcTextEscapement src_XwcTextEscapement
#define Xutf8TextEscapement src_Xutf8TextEscapement
#define XmbTextExtents src_XmbTextExtents
#define XwcTextExtents src_XwcTextExtents
#define Xutf8TextExtents src_Xutf8TextExtents
#define XmbTextPerCharExtents src_XmbTextPerCharExtents
#define XwcTextPerCharExtents src_XwcTextPerCharExtents
#define Xutf8TextPerCharExtents src_Xutf8TextPerCharExtents
#define XmbDrawText src_XmbDrawText
#define XwcDrawText src_XwcDrawText
#define Xutf8DrawText src_Xutf8DrawText
#define XmbDrawString src_XmbDrawString
#define XwcDrawString src_XwcDrawString
#define Xutf8DrawString src_Xutf8DrawString
#define XmbDrawImageString src_XmbDrawImageString
#define XwcDrawImageString src_XwcDrawImageString
#define Xutf8DrawImageString src_Xutf8DrawImageString
#define XOpenIM src_XOpenIM
#define XCloseIM src_XCloseIM
#define XDisplayOfIM src_XDisplayOfIM
#define XLocaleOfIM src_XLocaleOfIM
#define XDestroyIC src_XDestroyIC
#define XSetICFocus src_XSetICFocus
#define XUnsetICFocus src_XUnsetICFocus
#define XwcResetIC src_XwcResetIC
#define XmbResetIC src_XmbResetIC
#define Xutf8ResetIC src_Xutf8ResetIC
#define XIMOfIC src_XIMOfIC
#define XFilterEvent src_XFilterEvent
#define XmbLookupString src_XmbLookupString
#define XwcLookupString src_XwcLookupString
#define Xutf8LookupString src_Xutf8LookupString
#define XRegisterIMInstantiateCallback src_XRegisterIMInstantiateCallback
#define XUnregisterIMInstantiateCallback src_XUnregisterIMInstantiateCallback
#define XInternalConnectionNumbers src_XInternalConnectionNumbers
#define XProcessInternalConnection src_XProcessInternalConnection
#define XAddConnectionWatch src_XAddConnectionWatch
#define XRemoveConnectionWatch src_XRemoveConnectionWatch
#define XSetAuthorization src_XSetAuthorization
#define _Xmbtowc src__Xmbtowc
#define _Xwctomb src__Xwctomb
#define XGetEventData src_XGetEventData
#define XFreeEventData src_XFreeEventData
void loadXlib(void *(*load_fn)(const char* name)) {
    src__Xmblen = (PFN__Xmblen)load_fn("_Xmblen");
    src_XLoadQueryFont = (PFN_XLoadQueryFont)load_fn("XLoadQueryFont");
    src_XQueryFont = (PFN_XQueryFont)load_fn("XQueryFont");
    src_XGetMotionEvents = (PFN_XGetMotionEvents)load_fn("XGetMotionEvents");
    src_XDeleteModifiermapEntry = (PFN_XDeleteModifiermapEntry)load_fn("XDeleteModifiermapEntry");
    src_XGetModifierMapping = (PFN_XGetModifierMapping)load_fn("XGetModifierMapping");
    src_XInsertModifiermapEntry = (PFN_XInsertModifiermapEntry)load_fn("XInsertModifiermapEntry");
    src_XNewModifiermap = (PFN_XNewModifiermap)load_fn("XNewModifiermap");
    src_XCreateImage = (PFN_XCreateImage)load_fn("XCreateImage");
    src_XInitImage = (PFN_XInitImage)load_fn("XInitImage");
    src_XGetImage = (PFN_XGetImage)load_fn("XGetImage");
    src_XGetSubImage = (PFN_XGetSubImage)load_fn("XGetSubImage");
    src_XOpenDisplay = (PFN_XOpenDisplay)load_fn("XOpenDisplay");
    src_XrmInitialize = (PFN_XrmInitialize)load_fn("XrmInitialize");
    src_XFetchBytes = (PFN_XFetchBytes)load_fn("XFetchBytes");
    src_XFetchBuffer = (PFN_XFetchBuffer)load_fn("XFetchBuffer");
    src_XGetAtomName = (PFN_XGetAtomName)load_fn("XGetAtomName");
    src_XGetAtomNames = (PFN_XGetAtomNames)load_fn("XGetAtomNames");
    src_XGetDefault = (PFN_XGetDefault)load_fn("XGetDefault");
    src_XDisplayName = (PFN_XDisplayName)load_fn("XDisplayName");
    src_XKeysymToString = (PFN_XKeysymToString)load_fn("XKeysymToString");
    src_XInternAtom = (PFN_XInternAtom)load_fn("XInternAtom");
    src_XInternAtoms = (PFN_XInternAtoms)load_fn("XInternAtoms");
    src_XCopyColormapAndFree = (PFN_XCopyColormapAndFree)load_fn("XCopyColormapAndFree");
    src_XCreateColormap = (PFN_XCreateColormap)load_fn("XCreateColormap");
    src_XCreatePixmapCursor = (PFN_XCreatePixmapCursor)load_fn("XCreatePixmapCursor");
    src_XCreateGlyphCursor = (PFN_XCreateGlyphCursor)load_fn("XCreateGlyphCursor");
    src_XCreateFontCursor = (PFN_XCreateFontCursor)load_fn("XCreateFontCursor");
    src_XLoadFont = (PFN_XLoadFont)load_fn("XLoadFont");
    src_XCreateGC = (PFN_XCreateGC)load_fn("XCreateGC");
    src_XGContextFromGC = (PFN_XGContextFromGC)load_fn("XGContextFromGC");
    src_XFlushGC = (PFN_XFlushGC)load_fn("XFlushGC");
    src_XCreatePixmap = (PFN_XCreatePixmap)load_fn("XCreatePixmap");
    src_XCreateBitmapFromData = (PFN_XCreateBitmapFromData)load_fn("XCreateBitmapFromData");
    src_XCreatePixmapFromBitmapData = (PFN_XCreatePixmapFromBitmapData)load_fn("XCreatePixmapFromBitmapData");
    src_XCreateSimpleWindow = (PFN_XCreateSimpleWindow)load_fn("XCreateSimpleWindow");
    src_XGetSelectionOwner = (PFN_XGetSelectionOwner)load_fn("XGetSelectionOwner");
    src_XCreateWindow = (PFN_XCreateWindow)load_fn("XCreateWindow");
    src_XListInstalledColormaps = (PFN_XListInstalledColormaps)load_fn("XListInstalledColormaps");
    src_XListFonts = (PFN_XListFonts)load_fn("XListFonts");
    src_XListFontsWithInfo = (PFN_XListFontsWithInfo)load_fn("XListFontsWithInfo");
    src_XGetFontPath = (PFN_XGetFontPath)load_fn("XGetFontPath");
    src_XListExtensions = (PFN_XListExtensions)load_fn("XListExtensions");
    src_XListProperties = (PFN_XListProperties)load_fn("XListProperties");
    src_XListHosts = (PFN_XListHosts)load_fn("XListHosts");
    src_XKeycodeToKeysym = (PFN_XKeycodeToKeysym)load_fn("XKeycodeToKeysym");
    src_XLookupKeysym = (PFN_XLookupKeysym)load_fn("XLookupKeysym");
    src_XGetKeyboardMapping = (PFN_XGetKeyboardMapping)load_fn("XGetKeyboardMapping");
    src_XStringToKeysym = (PFN_XStringToKeysym)load_fn("XStringToKeysym");
    src_XMaxRequestSize = (PFN_XMaxRequestSize)load_fn("XMaxRequestSize");
    src_XExtendedMaxRequestSize = (PFN_XExtendedMaxRequestSize)load_fn("XExtendedMaxRequestSize");
    src_XResourceManagerString = (PFN_XResourceManagerString)load_fn("XResourceManagerString");
    src_XScreenResourceString = (PFN_XScreenResourceString)load_fn("XScreenResourceString");
    src_XDisplayMotionBufferSize = (PFN_XDisplayMotionBufferSize)load_fn("XDisplayMotionBufferSize");
    src_XVisualIDFromVisual = (PFN_XVisualIDFromVisual)load_fn("XVisualIDFromVisual");
    src_XInitThreads = (PFN_XInitThreads)load_fn("XInitThreads");
    src_XLockDisplay = (PFN_XLockDisplay)load_fn("XLockDisplay");
    src_XUnlockDisplay = (PFN_XUnlockDisplay)load_fn("XUnlockDisplay");
    src_XInitExtension = (PFN_XInitExtension)load_fn("XInitExtension");
    src_XAddExtension = (PFN_XAddExtension)load_fn("XAddExtension");
    src_XFindOnExtensionList = (PFN_XFindOnExtensionList)load_fn("XFindOnExtensionList");
    src_XEHeadOfExtensionList = (PFN_XEHeadOfExtensionList)load_fn("XEHeadOfExtensionList");
    src_XRootWindow = (PFN_XRootWindow)load_fn("XRootWindow");
    src_XDefaultRootWindow = (PFN_XDefaultRootWindow)load_fn("XDefaultRootWindow");
    src_XRootWindowOfScreen = (PFN_XRootWindowOfScreen)load_fn("XRootWindowOfScreen");
    src_XDefaultVisual = (PFN_XDefaultVisual)load_fn("XDefaultVisual");
    src_XDefaultVisualOfScreen = (PFN_XDefaultVisualOfScreen)load_fn("XDefaultVisualOfScreen");
    src_XDefaultGC = (PFN_XDefaultGC)load_fn("XDefaultGC");
    src_XDefaultGCOfScreen = (PFN_XDefaultGCOfScreen)load_fn("XDefaultGCOfScreen");
    src_XBlackPixel = (PFN_XBlackPixel)load_fn("XBlackPixel");
    src_XWhitePixel = (PFN_XWhitePixel)load_fn("XWhitePixel");
    src_XAllPlanes = (PFN_XAllPlanes)load_fn("XAllPlanes");
    src_XBlackPixelOfScreen = (PFN_XBlackPixelOfScreen)load_fn("XBlackPixelOfScreen");
    src_XWhitePixelOfScreen = (PFN_XWhitePixelOfScreen)load_fn("XWhitePixelOfScreen");
    src_XNextRequest = (PFN_XNextRequest)load_fn("XNextRequest");
    src_XLastKnownRequestProcessed = (PFN_XLastKnownRequestProcessed)load_fn("XLastKnownRequestProcessed");
    src_XServerVendor = (PFN_XServerVendor)load_fn("XServerVendor");
    src_XDisplayString = (PFN_XDisplayString)load_fn("XDisplayString");
    src_XDefaultColormap = (PFN_XDefaultColormap)load_fn("XDefaultColormap");
    src_XDefaultColormapOfScreen = (PFN_XDefaultColormapOfScreen)load_fn("XDefaultColormapOfScreen");
    src_XDisplayOfScreen = (PFN_XDisplayOfScreen)load_fn("XDisplayOfScreen");
    src_XScreenOfDisplay = (PFN_XScreenOfDisplay)load_fn("XScreenOfDisplay");
    src_XDefaultScreenOfDisplay = (PFN_XDefaultScreenOfDisplay)load_fn("XDefaultScreenOfDisplay");
    src_XEventMaskOfScreen = (PFN_XEventMaskOfScreen)load_fn("XEventMaskOfScreen");
    src_XScreenNumberOfScreen = (PFN_XScreenNumberOfScreen)load_fn("XScreenNumberOfScreen");
    src_XSetErrorHandler = (PFN_XSetErrorHandler)load_fn("XSetErrorHandler");
    src_XSetIOErrorHandler = (PFN_XSetIOErrorHandler)load_fn("XSetIOErrorHandler");
    src_XSetIOErrorExitHandler = (PFN_XSetIOErrorExitHandler)load_fn("XSetIOErrorExitHandler");
    src_XListPixmapFormats = (PFN_XListPixmapFormats)load_fn("XListPixmapFormats");
    src_XListDepths = (PFN_XListDepths)load_fn("XListDepths");
    src_XReconfigureWMWindow = (PFN_XReconfigureWMWindow)load_fn("XReconfigureWMWindow");
    src_XGetWMProtocols = (PFN_XGetWMProtocols)load_fn("XGetWMProtocols");
    src_XSetWMProtocols = (PFN_XSetWMProtocols)load_fn("XSetWMProtocols");
    src_XIconifyWindow = (PFN_XIconifyWindow)load_fn("XIconifyWindow");
    src_XWithdrawWindow = (PFN_XWithdrawWindow)load_fn("XWithdrawWindow");
    src_XGetCommand = (PFN_XGetCommand)load_fn("XGetCommand");
    src_XGetWMColormapWindows = (PFN_XGetWMColormapWindows)load_fn("XGetWMColormapWindows");
    src_XSetWMColormapWindows = (PFN_XSetWMColormapWindows)load_fn("XSetWMColormapWindows");
    src_XFreeStringList = (PFN_XFreeStringList)load_fn("XFreeStringList");
    src_XSetTransientForHint = (PFN_XSetTransientForHint)load_fn("XSetTransientForHint");
    src_XActivateScreenSaver = (PFN_XActivateScreenSaver)load_fn("XActivateScreenSaver");
    src_XAddHost = (PFN_XAddHost)load_fn("XAddHost");
    src_XAddHosts = (PFN_XAddHosts)load_fn("XAddHosts");
    src_XAddToExtensionList = (PFN_XAddToExtensionList)load_fn("XAddToExtensionList");
    src_XAddToSaveSet = (PFN_XAddToSaveSet)load_fn("XAddToSaveSet");
    src_XAllocColor = (PFN_XAllocColor)load_fn("XAllocColor");
    src_XAllocColorCells = (PFN_XAllocColorCells)load_fn("XAllocColorCells");
    src_XAllocColorPlanes = (PFN_XAllocColorPlanes)load_fn("XAllocColorPlanes");
    src_XAllocNamedColor = (PFN_XAllocNamedColor)load_fn("XAllocNamedColor");
    src_XAllowEvents = (PFN_XAllowEvents)load_fn("XAllowEvents");
    src_XAutoRepeatOff = (PFN_XAutoRepeatOff)load_fn("XAutoRepeatOff");
    src_XAutoRepeatOn = (PFN_XAutoRepeatOn)load_fn("XAutoRepeatOn");
    src_XBell = (PFN_XBell)load_fn("XBell");
    src_XBitmapBitOrder = (PFN_XBitmapBitOrder)load_fn("XBitmapBitOrder");
    src_XBitmapPad = (PFN_XBitmapPad)load_fn("XBitmapPad");
    src_XBitmapUnit = (PFN_XBitmapUnit)load_fn("XBitmapUnit");
    src_XCellsOfScreen = (PFN_XCellsOfScreen)load_fn("XCellsOfScreen");
    src_XChangeActivePointerGrab = (PFN_XChangeActivePointerGrab)load_fn("XChangeActivePointerGrab");
    src_XChangeGC = (PFN_XChangeGC)load_fn("XChangeGC");
    src_XChangeKeyboardControl = (PFN_XChangeKeyboardControl)load_fn("XChangeKeyboardControl");
    src_XChangeKeyboardMapping = (PFN_XChangeKeyboardMapping)load_fn("XChangeKeyboardMapping");
    src_XChangePointerControl = (PFN_XChangePointerControl)load_fn("XChangePointerControl");
    src_XChangeProperty = (PFN_XChangeProperty)load_fn("XChangeProperty");
    src_XChangeSaveSet = (PFN_XChangeSaveSet)load_fn("XChangeSaveSet");
    src_XChangeWindowAttributes = (PFN_XChangeWindowAttributes)load_fn("XChangeWindowAttributes");
    src_XCheckMaskEvent = (PFN_XCheckMaskEvent)load_fn("XCheckMaskEvent");
    src_XCheckTypedEvent = (PFN_XCheckTypedEvent)load_fn("XCheckTypedEvent");
    src_XCheckTypedWindowEvent = (PFN_XCheckTypedWindowEvent)load_fn("XCheckTypedWindowEvent");
    src_XCheckWindowEvent = (PFN_XCheckWindowEvent)load_fn("XCheckWindowEvent");
    src_XCirculateSubwindows = (PFN_XCirculateSubwindows)load_fn("XCirculateSubwindows");
    src_XCirculateSubwindowsDown = (PFN_XCirculateSubwindowsDown)load_fn("XCirculateSubwindowsDown");
    src_XCirculateSubwindowsUp = (PFN_XCirculateSubwindowsUp)load_fn("XCirculateSubwindowsUp");
    src_XClearArea = (PFN_XClearArea)load_fn("XClearArea");
    src_XClearWindow = (PFN_XClearWindow)load_fn("XClearWindow");
    src_XCloseDisplay = (PFN_XCloseDisplay)load_fn("XCloseDisplay");
    src_XConfigureWindow = (PFN_XConfigureWindow)load_fn("XConfigureWindow");
    src_XConnectionNumber = (PFN_XConnectionNumber)load_fn("XConnectionNumber");
    src_XConvertSelection = (PFN_XConvertSelection)load_fn("XConvertSelection");
    src_XCopyArea = (PFN_XCopyArea)load_fn("XCopyArea");
    src_XCopyGC = (PFN_XCopyGC)load_fn("XCopyGC");
    src_XCopyPlane = (PFN_XCopyPlane)load_fn("XCopyPlane");
    src_XDefaultDepth = (PFN_XDefaultDepth)load_fn("XDefaultDepth");
    src_XDefaultDepthOfScreen = (PFN_XDefaultDepthOfScreen)load_fn("XDefaultDepthOfScreen");
    src_XDefaultScreen = (PFN_XDefaultScreen)load_fn("XDefaultScreen");
    src_XDefineCursor = (PFN_XDefineCursor)load_fn("XDefineCursor");
    src_XDeleteProperty = (PFN_XDeleteProperty)load_fn("XDeleteProperty");
    src_XDestroyWindow = (PFN_XDestroyWindow)load_fn("XDestroyWindow");
    src_XDestroySubwindows = (PFN_XDestroySubwindows)load_fn("XDestroySubwindows");
    src_XDoesBackingStore = (PFN_XDoesBackingStore)load_fn("XDoesBackingStore");
    src_XDoesSaveUnders = (PFN_XDoesSaveUnders)load_fn("XDoesSaveUnders");
    src_XDisableAccessControl = (PFN_XDisableAccessControl)load_fn("XDisableAccessControl");
    src_XDisplayCells = (PFN_XDisplayCells)load_fn("XDisplayCells");
    src_XDisplayHeight = (PFN_XDisplayHeight)load_fn("XDisplayHeight");
    src_XDisplayHeightMM = (PFN_XDisplayHeightMM)load_fn("XDisplayHeightMM");
    src_XDisplayKeycodes = (PFN_XDisplayKeycodes)load_fn("XDisplayKeycodes");
    src_XDisplayPlanes = (PFN_XDisplayPlanes)load_fn("XDisplayPlanes");
    src_XDisplayWidth = (PFN_XDisplayWidth)load_fn("XDisplayWidth");
    src_XDisplayWidthMM = (PFN_XDisplayWidthMM)load_fn("XDisplayWidthMM");
    src_XDrawArc = (PFN_XDrawArc)load_fn("XDrawArc");
    src_XDrawArcs = (PFN_XDrawArcs)load_fn("XDrawArcs");
    src_XDrawImageString = (PFN_XDrawImageString)load_fn("XDrawImageString");
    src_XDrawImageString16 = (PFN_XDrawImageString16)load_fn("XDrawImageString16");
    src_XDrawLine = (PFN_XDrawLine)load_fn("XDrawLine");
    src_XDrawLines = (PFN_XDrawLines)load_fn("XDrawLines");
    src_XDrawPoint = (PFN_XDrawPoint)load_fn("XDrawPoint");
    src_XDrawPoints = (PFN_XDrawPoints)load_fn("XDrawPoints");
    src_XDrawRectangle = (PFN_XDrawRectangle)load_fn("XDrawRectangle");
    src_XDrawRectangles = (PFN_XDrawRectangles)load_fn("XDrawRectangles");
    src_XDrawSegments = (PFN_XDrawSegments)load_fn("XDrawSegments");
    src_XDrawString = (PFN_XDrawString)load_fn("XDrawString");
    src_XDrawString16 = (PFN_XDrawString16)load_fn("XDrawString16");
    src_XDrawText = (PFN_XDrawText)load_fn("XDrawText");
    src_XDrawText16 = (PFN_XDrawText16)load_fn("XDrawText16");
    src_XEnableAccessControl = (PFN_XEnableAccessControl)load_fn("XEnableAccessControl");
    src_XEventsQueued = (PFN_XEventsQueued)load_fn("XEventsQueued");
    src_XFetchName = (PFN_XFetchName)load_fn("XFetchName");
    src_XFillArc = (PFN_XFillArc)load_fn("XFillArc");
    src_XFillArcs = (PFN_XFillArcs)load_fn("XFillArcs");
    src_XFillPolygon = (PFN_XFillPolygon)load_fn("XFillPolygon");
    src_XFillRectangle = (PFN_XFillRectangle)load_fn("XFillRectangle");
    src_XFillRectangles = (PFN_XFillRectangles)load_fn("XFillRectangles");
    src_XFlush = (PFN_XFlush)load_fn("XFlush");
    src_XForceScreenSaver = (PFN_XForceScreenSaver)load_fn("XForceScreenSaver");
    src_XFree = (PFN_XFree)load_fn("XFree");
    src_XFreeColormap = (PFN_XFreeColormap)load_fn("XFreeColormap");
    src_XFreeColors = (PFN_XFreeColors)load_fn("XFreeColors");
    src_XFreeCursor = (PFN_XFreeCursor)load_fn("XFreeCursor");
    src_XFreeExtensionList = (PFN_XFreeExtensionList)load_fn("XFreeExtensionList");
    src_XFreeFont = (PFN_XFreeFont)load_fn("XFreeFont");
    src_XFreeFontInfo = (PFN_XFreeFontInfo)load_fn("XFreeFontInfo");
    src_XFreeFontNames = (PFN_XFreeFontNames)load_fn("XFreeFontNames");
    src_XFreeFontPath = (PFN_XFreeFontPath)load_fn("XFreeFontPath");
    src_XFreeGC = (PFN_XFreeGC)load_fn("XFreeGC");
    src_XFreeModifiermap = (PFN_XFreeModifiermap)load_fn("XFreeModifiermap");
    src_XFreePixmap = (PFN_XFreePixmap)load_fn("XFreePixmap");
    src_XGeometry = (PFN_XGeometry)load_fn("XGeometry");
    src_XGetErrorDatabaseText = (PFN_XGetErrorDatabaseText)load_fn("XGetErrorDatabaseText");
    src_XGetErrorText = (PFN_XGetErrorText)load_fn("XGetErrorText");
    src_XGetFontProperty = (PFN_XGetFontProperty)load_fn("XGetFontProperty");
    src_XGetGCValues = (PFN_XGetGCValues)load_fn("XGetGCValues");
    src_XGetGeometry = (PFN_XGetGeometry)load_fn("XGetGeometry");
    src_XGetIconName = (PFN_XGetIconName)load_fn("XGetIconName");
    src_XGetInputFocus = (PFN_XGetInputFocus)load_fn("XGetInputFocus");
    src_XGetKeyboardControl = (PFN_XGetKeyboardControl)load_fn("XGetKeyboardControl");
    src_XGetPointerControl = (PFN_XGetPointerControl)load_fn("XGetPointerControl");
    src_XGetPointerMapping = (PFN_XGetPointerMapping)load_fn("XGetPointerMapping");
    src_XGetScreenSaver = (PFN_XGetScreenSaver)load_fn("XGetScreenSaver");
    src_XGetTransientForHint = (PFN_XGetTransientForHint)load_fn("XGetTransientForHint");
    src_XGetWindowProperty = (PFN_XGetWindowProperty)load_fn("XGetWindowProperty");
    src_XGetWindowAttributes = (PFN_XGetWindowAttributes)load_fn("XGetWindowAttributes");
    src_XGrabButton = (PFN_XGrabButton)load_fn("XGrabButton");
    src_XGrabKey = (PFN_XGrabKey)load_fn("XGrabKey");
    src_XGrabKeyboard = (PFN_XGrabKeyboard)load_fn("XGrabKeyboard");
    src_XGrabPointer = (PFN_XGrabPointer)load_fn("XGrabPointer");
    src_XGrabServer = (PFN_XGrabServer)load_fn("XGrabServer");
    src_XHeightMMOfScreen = (PFN_XHeightMMOfScreen)load_fn("XHeightMMOfScreen");
    src_XHeightOfScreen = (PFN_XHeightOfScreen)load_fn("XHeightOfScreen");
    src_XImageByteOrder = (PFN_XImageByteOrder)load_fn("XImageByteOrder");
    src_XInstallColormap = (PFN_XInstallColormap)load_fn("XInstallColormap");
    src_XKeysymToKeycode = (PFN_XKeysymToKeycode)load_fn("XKeysymToKeycode");
    src_XKillClient = (PFN_XKillClient)load_fn("XKillClient");
    src_XLookupColor = (PFN_XLookupColor)load_fn("XLookupColor");
    src_XLowerWindow = (PFN_XLowerWindow)load_fn("XLowerWindow");
    src_XMapRaised = (PFN_XMapRaised)load_fn("XMapRaised");
    src_XMapSubwindows = (PFN_XMapSubwindows)load_fn("XMapSubwindows");
    src_XMapWindow = (PFN_XMapWindow)load_fn("XMapWindow");
    src_XMaskEvent = (PFN_XMaskEvent)load_fn("XMaskEvent");
    src_XMaxCmapsOfScreen = (PFN_XMaxCmapsOfScreen)load_fn("XMaxCmapsOfScreen");
    src_XMinCmapsOfScreen = (PFN_XMinCmapsOfScreen)load_fn("XMinCmapsOfScreen");
    src_XMoveResizeWindow = (PFN_XMoveResizeWindow)load_fn("XMoveResizeWindow");
    src_XMoveWindow = (PFN_XMoveWindow)load_fn("XMoveWindow");
    src_XNextEvent = (PFN_XNextEvent)load_fn("XNextEvent");
    src_XNoOp = (PFN_XNoOp)load_fn("XNoOp");
    src_XParseColor = (PFN_XParseColor)load_fn("XParseColor");
    src_XParseGeometry = (PFN_XParseGeometry)load_fn("XParseGeometry");
    src_XPeekEvent = (PFN_XPeekEvent)load_fn("XPeekEvent");
    src_XPending = (PFN_XPending)load_fn("XPending");
    src_XPlanesOfScreen = (PFN_XPlanesOfScreen)load_fn("XPlanesOfScreen");
    src_XProtocolRevision = (PFN_XProtocolRevision)load_fn("XProtocolRevision");
    src_XProtocolVersion = (PFN_XProtocolVersion)load_fn("XProtocolVersion");
    src_XPutBackEvent = (PFN_XPutBackEvent)load_fn("XPutBackEvent");
    src_XPutImage = (PFN_XPutImage)load_fn("XPutImage");
    src_XQLength = (PFN_XQLength)load_fn("XQLength");
    src_XQueryBestCursor = (PFN_XQueryBestCursor)load_fn("XQueryBestCursor");
    src_XQueryBestSize = (PFN_XQueryBestSize)load_fn("XQueryBestSize");
    src_XQueryBestStipple = (PFN_XQueryBestStipple)load_fn("XQueryBestStipple");
    src_XQueryBestTile = (PFN_XQueryBestTile)load_fn("XQueryBestTile");
    src_XQueryColor = (PFN_XQueryColor)load_fn("XQueryColor");
    src_XQueryColors = (PFN_XQueryColors)load_fn("XQueryColors");
    src_XQueryExtension = (PFN_XQueryExtension)load_fn("XQueryExtension");
    src_XQueryKeymap = (PFN_XQueryKeymap)load_fn("XQueryKeymap");
    src_XQueryPointer = (PFN_XQueryPointer)load_fn("XQueryPointer");
    src_XQueryTextExtents = (PFN_XQueryTextExtents)load_fn("XQueryTextExtents");
    src_XQueryTextExtents16 = (PFN_XQueryTextExtents16)load_fn("XQueryTextExtents16");
    src_XQueryTree = (PFN_XQueryTree)load_fn("XQueryTree");
    src_XRaiseWindow = (PFN_XRaiseWindow)load_fn("XRaiseWindow");
    src_XReadBitmapFile = (PFN_XReadBitmapFile)load_fn("XReadBitmapFile");
    src_XReadBitmapFileData = (PFN_XReadBitmapFileData)load_fn("XReadBitmapFileData");
    src_XRebindKeysym = (PFN_XRebindKeysym)load_fn("XRebindKeysym");
    src_XRecolorCursor = (PFN_XRecolorCursor)load_fn("XRecolorCursor");
    src_XRefreshKeyboardMapping = (PFN_XRefreshKeyboardMapping)load_fn("XRefreshKeyboardMapping");
    src_XRemoveFromSaveSet = (PFN_XRemoveFromSaveSet)load_fn("XRemoveFromSaveSet");
    src_XRemoveHost = (PFN_XRemoveHost)load_fn("XRemoveHost");
    src_XRemoveHosts = (PFN_XRemoveHosts)load_fn("XRemoveHosts");
    src_XReparentWindow = (PFN_XReparentWindow)load_fn("XReparentWindow");
    src_XResetScreenSaver = (PFN_XResetScreenSaver)load_fn("XResetScreenSaver");
    src_XResizeWindow = (PFN_XResizeWindow)load_fn("XResizeWindow");
    src_XRestackWindows = (PFN_XRestackWindows)load_fn("XRestackWindows");
    src_XRotateBuffers = (PFN_XRotateBuffers)load_fn("XRotateBuffers");
    src_XRotateWindowProperties = (PFN_XRotateWindowProperties)load_fn("XRotateWindowProperties");
    src_XScreenCount = (PFN_XScreenCount)load_fn("XScreenCount");
    src_XSelectInput = (PFN_XSelectInput)load_fn("XSelectInput");
    src_XSendEvent = (PFN_XSendEvent)load_fn("XSendEvent");
    src_XSetAccessControl = (PFN_XSetAccessControl)load_fn("XSetAccessControl");
    src_XSetArcMode = (PFN_XSetArcMode)load_fn("XSetArcMode");
    src_XSetBackground = (PFN_XSetBackground)load_fn("XSetBackground");
    src_XSetClipMask = (PFN_XSetClipMask)load_fn("XSetClipMask");
    src_XSetClipOrigin = (PFN_XSetClipOrigin)load_fn("XSetClipOrigin");
    src_XSetClipRectangles = (PFN_XSetClipRectangles)load_fn("XSetClipRectangles");
    src_XSetCloseDownMode = (PFN_XSetCloseDownMode)load_fn("XSetCloseDownMode");
    src_XSetCommand = (PFN_XSetCommand)load_fn("XSetCommand");
    src_XSetDashes = (PFN_XSetDashes)load_fn("XSetDashes");
    src_XSetFillRule = (PFN_XSetFillRule)load_fn("XSetFillRule");
    src_XSetFillStyle = (PFN_XSetFillStyle)load_fn("XSetFillStyle");
    src_XSetFont = (PFN_XSetFont)load_fn("XSetFont");
    src_XSetFontPath = (PFN_XSetFontPath)load_fn("XSetFontPath");
    src_XSetForeground = (PFN_XSetForeground)load_fn("XSetForeground");
    src_XSetFunction = (PFN_XSetFunction)load_fn("XSetFunction");
    src_XSetGraphicsExposures = (PFN_XSetGraphicsExposures)load_fn("XSetGraphicsExposures");
    src_XSetIconName = (PFN_XSetIconName)load_fn("XSetIconName");
    src_XSetInputFocus = (PFN_XSetInputFocus)load_fn("XSetInputFocus");
    src_XSetLineAttributes = (PFN_XSetLineAttributes)load_fn("XSetLineAttributes");
    src_XSetModifierMapping = (PFN_XSetModifierMapping)load_fn("XSetModifierMapping");
    src_XSetPlaneMask = (PFN_XSetPlaneMask)load_fn("XSetPlaneMask");
    src_XSetPointerMapping = (PFN_XSetPointerMapping)load_fn("XSetPointerMapping");
    src_XSetScreenSaver = (PFN_XSetScreenSaver)load_fn("XSetScreenSaver");
    src_XSetSelectionOwner = (PFN_XSetSelectionOwner)load_fn("XSetSelectionOwner");
    src_XSetState = (PFN_XSetState)load_fn("XSetState");
    src_XSetStipple = (PFN_XSetStipple)load_fn("XSetStipple");
    src_XSetSubwindowMode = (PFN_XSetSubwindowMode)load_fn("XSetSubwindowMode");
    src_XSetTSOrigin = (PFN_XSetTSOrigin)load_fn("XSetTSOrigin");
    src_XSetTile = (PFN_XSetTile)load_fn("XSetTile");
    src_XSetWindowBackground = (PFN_XSetWindowBackground)load_fn("XSetWindowBackground");
    src_XSetWindowBackgroundPixmap = (PFN_XSetWindowBackgroundPixmap)load_fn("XSetWindowBackgroundPixmap");
    src_XSetWindowBorder = (PFN_XSetWindowBorder)load_fn("XSetWindowBorder");
    src_XSetWindowBorderPixmap = (PFN_XSetWindowBorderPixmap)load_fn("XSetWindowBorderPixmap");
    src_XSetWindowBorderWidth = (PFN_XSetWindowBorderWidth)load_fn("XSetWindowBorderWidth");
    src_XSetWindowColormap = (PFN_XSetWindowColormap)load_fn("XSetWindowColormap");
    src_XStoreBuffer = (PFN_XStoreBuffer)load_fn("XStoreBuffer");
    src_XStoreBytes = (PFN_XStoreBytes)load_fn("XStoreBytes");
    src_XStoreColor = (PFN_XStoreColor)load_fn("XStoreColor");
    src_XStoreColors = (PFN_XStoreColors)load_fn("XStoreColors");
    src_XStoreName = (PFN_XStoreName)load_fn("XStoreName");
    src_XStoreNamedColor = (PFN_XStoreNamedColor)load_fn("XStoreNamedColor");
    src_XSync = (PFN_XSync)load_fn("XSync");
    src_XTextExtents = (PFN_XTextExtents)load_fn("XTextExtents");
    src_XTextExtents16 = (PFN_XTextExtents16)load_fn("XTextExtents16");
    src_XTextWidth = (PFN_XTextWidth)load_fn("XTextWidth");
    src_XTextWidth16 = (PFN_XTextWidth16)load_fn("XTextWidth16");
    src_XTranslateCoordinates = (PFN_XTranslateCoordinates)load_fn("XTranslateCoordinates");
    src_XUndefineCursor = (PFN_XUndefineCursor)load_fn("XUndefineCursor");
    src_XUngrabButton = (PFN_XUngrabButton)load_fn("XUngrabButton");
    src_XUngrabKey = (PFN_XUngrabKey)load_fn("XUngrabKey");
    src_XUngrabKeyboard = (PFN_XUngrabKeyboard)load_fn("XUngrabKeyboard");
    src_XUngrabPointer = (PFN_XUngrabPointer)load_fn("XUngrabPointer");
    src_XUngrabServer = (PFN_XUngrabServer)load_fn("XUngrabServer");
    src_XUninstallColormap = (PFN_XUninstallColormap)load_fn("XUninstallColormap");
    src_XUnloadFont = (PFN_XUnloadFont)load_fn("XUnloadFont");
    src_XUnmapSubwindows = (PFN_XUnmapSubwindows)load_fn("XUnmapSubwindows");
    src_XUnmapWindow = (PFN_XUnmapWindow)load_fn("XUnmapWindow");
    src_XVendorRelease = (PFN_XVendorRelease)load_fn("XVendorRelease");
    src_XWarpPointer = (PFN_XWarpPointer)load_fn("XWarpPointer");
    src_XWidthMMOfScreen = (PFN_XWidthMMOfScreen)load_fn("XWidthMMOfScreen");
    src_XWidthOfScreen = (PFN_XWidthOfScreen)load_fn("XWidthOfScreen");
    src_XWindowEvent = (PFN_XWindowEvent)load_fn("XWindowEvent");
    src_XWriteBitmapFile = (PFN_XWriteBitmapFile)load_fn("XWriteBitmapFile");
    src_XSupportsLocale = (PFN_XSupportsLocale)load_fn("XSupportsLocale");
    src_XSetLocaleModifiers = (PFN_XSetLocaleModifiers)load_fn("XSetLocaleModifiers");
    src_XOpenOM = (PFN_XOpenOM)load_fn("XOpenOM");
    src_XCloseOM = (PFN_XCloseOM)load_fn("XCloseOM");
    src_XDisplayOfOM = (PFN_XDisplayOfOM)load_fn("XDisplayOfOM");
    src_XLocaleOfOM = (PFN_XLocaleOfOM)load_fn("XLocaleOfOM");
    src_XDestroyOC = (PFN_XDestroyOC)load_fn("XDestroyOC");
    src_XOMOfOC = (PFN_XOMOfOC)load_fn("XOMOfOC");
    src_XCreateFontSet = (PFN_XCreateFontSet)load_fn("XCreateFontSet");
    src_XFreeFontSet = (PFN_XFreeFontSet)load_fn("XFreeFontSet");
    src_XFontsOfFontSet = (PFN_XFontsOfFontSet)load_fn("XFontsOfFontSet");
    src_XBaseFontNameListOfFontSet = (PFN_XBaseFontNameListOfFontSet)load_fn("XBaseFontNameListOfFontSet");
    src_XLocaleOfFontSet = (PFN_XLocaleOfFontSet)load_fn("XLocaleOfFontSet");
    src_XContextDependentDrawing = (PFN_XContextDependentDrawing)load_fn("XContextDependentDrawing");
    src_XDirectionalDependentDrawing = (PFN_XDirectionalDependentDrawing)load_fn("XDirectionalDependentDrawing");
    src_XContextualDrawing = (PFN_XContextualDrawing)load_fn("XContextualDrawing");
    src_XExtentsOfFontSet = (PFN_XExtentsOfFontSet)load_fn("XExtentsOfFontSet");
    src_XmbTextEscapement = (PFN_XmbTextEscapement)load_fn("XmbTextEscapement");
    src_XwcTextEscapement = (PFN_XwcTextEscapement)load_fn("XwcTextEscapement");
    src_Xutf8TextEscapement = (PFN_Xutf8TextEscapement)load_fn("Xutf8TextEscapement");
    src_XmbTextExtents = (PFN_XmbTextExtents)load_fn("XmbTextExtents");
    src_XwcTextExtents = (PFN_XwcTextExtents)load_fn("XwcTextExtents");
    src_Xutf8TextExtents = (PFN_Xutf8TextExtents)load_fn("Xutf8TextExtents");
    src_XmbTextPerCharExtents = (PFN_XmbTextPerCharExtents)load_fn("XmbTextPerCharExtents");
    src_XwcTextPerCharExtents = (PFN_XwcTextPerCharExtents)load_fn("XwcTextPerCharExtents");
    src_Xutf8TextPerCharExtents = (PFN_Xutf8TextPerCharExtents)load_fn("Xutf8TextPerCharExtents");
    src_XmbDrawText = (PFN_XmbDrawText)load_fn("XmbDrawText");
    src_XwcDrawText = (PFN_XwcDrawText)load_fn("XwcDrawText");
    src_Xutf8DrawText = (PFN_Xutf8DrawText)load_fn("Xutf8DrawText");
    src_XmbDrawString = (PFN_XmbDrawString)load_fn("XmbDrawString");
    src_XwcDrawString = (PFN_XwcDrawString)load_fn("XwcDrawString");
    src_Xutf8DrawString = (PFN_Xutf8DrawString)load_fn("Xutf8DrawString");
    src_XmbDrawImageString = (PFN_XmbDrawImageString)load_fn("XmbDrawImageString");
    src_XwcDrawImageString = (PFN_XwcDrawImageString)load_fn("XwcDrawImageString");
    src_Xutf8DrawImageString = (PFN_Xutf8DrawImageString)load_fn("Xutf8DrawImageString");
    src_XOpenIM = (PFN_XOpenIM)load_fn("XOpenIM");
    src_XCloseIM = (PFN_XCloseIM)load_fn("XCloseIM");
    src_XDisplayOfIM = (PFN_XDisplayOfIM)load_fn("XDisplayOfIM");
    src_XLocaleOfIM = (PFN_XLocaleOfIM)load_fn("XLocaleOfIM");
    src_XDestroyIC = (PFN_XDestroyIC)load_fn("XDestroyIC");
    src_XSetICFocus = (PFN_XSetICFocus)load_fn("XSetICFocus");
    src_XUnsetICFocus = (PFN_XUnsetICFocus)load_fn("XUnsetICFocus");
    src_XwcResetIC = (PFN_XwcResetIC)load_fn("XwcResetIC");
    src_XmbResetIC = (PFN_XmbResetIC)load_fn("XmbResetIC");
    src_Xutf8ResetIC = (PFN_Xutf8ResetIC)load_fn("Xutf8ResetIC");
    src_XIMOfIC = (PFN_XIMOfIC)load_fn("XIMOfIC");
    src_XFilterEvent = (PFN_XFilterEvent)load_fn("XFilterEvent");
    src_XmbLookupString = (PFN_XmbLookupString)load_fn("XmbLookupString");
    src_XwcLookupString = (PFN_XwcLookupString)load_fn("XwcLookupString");
    src_Xutf8LookupString = (PFN_Xutf8LookupString)load_fn("Xutf8LookupString");
    src_XRegisterIMInstantiateCallback = (PFN_XRegisterIMInstantiateCallback)load_fn("XRegisterIMInstantiateCallback");
    src_XUnregisterIMInstantiateCallback = (PFN_XUnregisterIMInstantiateCallback)load_fn("XUnregisterIMInstantiateCallback");
    src_XInternalConnectionNumbers = (PFN_XInternalConnectionNumbers)load_fn("XInternalConnectionNumbers");
    src_XProcessInternalConnection = (PFN_XProcessInternalConnection)load_fn("XProcessInternalConnection");
    src_XAddConnectionWatch = (PFN_XAddConnectionWatch)load_fn("XAddConnectionWatch");
    src_XRemoveConnectionWatch = (PFN_XRemoveConnectionWatch)load_fn("XRemoveConnectionWatch");
    src_XSetAuthorization = (PFN_XSetAuthorization)load_fn("XSetAuthorization");
    src__Xmbtowc = (PFN__Xmbtowc)load_fn("_Xmbtowc");
    src__Xwctomb = (PFN__Xwctomb)load_fn("_Xwctomb");
    src_XGetEventData = (PFN_XGetEventData)load_fn("XGetEventData");
    src_XFreeEventData = (PFN_XFreeEventData)load_fn("XFreeEventData");
}