#include <X11/extensions/Xrandr.h>

// This file was generated by AutoDynamicHeader: https://github.com/bluesillybeard/AutoDynamicHeader and modified

typedef Bool(*PFN_XRRQueryExtension)(Display* dpy,
			int* event_base_return,
			int* error_base_return);
typedef Status(*PFN_XRRQueryVersion)(Display* dpy,
			    int* major_version_return,
			    int* minor_version_return);
typedef XRRScreenConfiguration*(*PFN_XRRGetScreenInfo)(Display* dpy,
					  Window window);
typedef void(*PFN_XRRFreeScreenConfigInfo)(XRRScreenConfiguration* config);
typedef Status(*PFN_XRRSetScreenConfig)(Display* dpy,
			   XRRScreenConfiguration* config,
			   Drawable draw,
			   int size_index,
			   Rotation rotation,
			   Time timestamp);
typedef Status(*PFN_XRRSetScreenConfigAndRate)(Display* dpy,
				  XRRScreenConfiguration* config,
				  Drawable draw,
				  int size_index,
				  Rotation rotation,
				  short rate,
				  Time timestamp);
typedef Rotation(*PFN_XRRConfigRotations)(XRRScreenConfiguration* config, Rotation* current_rotation);
typedef Time(*PFN_XRRConfigTimes)(XRRScreenConfiguration* config, Time* config_timestamp);
typedef XRRScreenSize*(*PFN_XRRConfigSizes)(XRRScreenConfiguration* config, int* nsizes);
typedef short*(*PFN_XRRConfigRates)(XRRScreenConfiguration* config, int sizeID, int* nrates);
typedef SizeID(*PFN_XRRConfigCurrentConfiguration)(XRRScreenConfiguration* config,
			      Rotation* rotation);
typedef short(*PFN_XRRConfigCurrentRate)(XRRScreenConfiguration* config);
typedef int(*PFN_XRRRootToScreen)(Display* dpy, Window root);
typedef void(*PFN_XRRSelectInput)(Display* dpy, Window window, int mask);
typedef Rotation(*PFN_XRRRotations)(Display* dpy, int screen, Rotation* current_rotation);
typedef XRRScreenSize*(*PFN_XRRSizes)(Display* dpy, int screen, int* nsizes);
typedef short*(*PFN_XRRRates)(Display* dpy, int screen, int sizeID, int* nrates);
typedef Time(*PFN_XRRTimes)(Display* dpy, int screen, Time* config_timestamp);
typedef Status(*PFN_XRRGetScreenSizeRange)(Display* dpy, Window window,
		       int* minWidth, int* minHeight,
		       int* maxWidth, int* maxHeight);
typedef void(*PFN_XRRSetScreenSize)(Display* dpy, Window window,
		  int width, int height,
		  int mmWidth, int mmHeight);
typedef XRRScreenResources*(*PFN_XRRGetScreenResources)(Display* dpy, Window window);
typedef void(*PFN_XRRFreeScreenResources)(XRRScreenResources* resources);
typedef XRROutputInfo*(*PFN_XRRGetOutputInfo)(Display* dpy, XRRScreenResources* resources, RROutput output);
typedef void(*PFN_XRRFreeOutputInfo)(XRROutputInfo* outputInfo);
typedef Atom*(*PFN_XRRListOutputProperties)(Display* dpy, RROutput output, int* nprop);
typedef XRRPropertyInfo*(*PFN_XRRQueryOutputProperty)(Display* dpy, RROutput output, Atom property);
typedef void(*PFN_XRRConfigureOutputProperty)(Display* dpy, RROutput output, Atom property,
			    Bool pending, Bool range, int num_values,
			    long* values);
typedef void(*PFN_XRRChangeOutputProperty)(Display* dpy, RROutput output,
			 Atom property, Atom type,
			 int format, int mode,
			 _Xconst unsigned char* data, int nelements);
typedef void(*PFN_XRRDeleteOutputProperty)(Display* dpy, RROutput output, Atom property);
typedef int(*PFN_XRRGetOutputProperty)(Display* dpy, RROutput output,
		      Atom property, long offset, long length,
		      Bool _delete, Bool pending, Atom req_type,
		      Atom* actual_type, int* actual_format,
		      unsigned long* nitems, unsigned long* bytes_after,
		      unsigned char** prop);
typedef XRRModeInfo*(*PFN_XRRAllocModeInfo)(_Xconst char* name, int nameLength);
typedef RRMode(*PFN_XRRCreateMode)(Display* dpy, Window window, XRRModeInfo* modeInfo);
typedef void(*PFN_XRRDestroyMode)(Display* dpy, RRMode mode);
typedef void(*PFN_XRRAddOutputMode)(Display* dpy, RROutput output, RRMode mode);
typedef void(*PFN_XRRDeleteOutputMode)(Display* dpy, RROutput output, RRMode mode);
typedef void(*PFN_XRRFreeModeInfo)(XRRModeInfo* modeInfo);
typedef XRRCrtcInfo*(*PFN_XRRGetCrtcInfo)(Display* dpy, XRRScreenResources* resources, RRCrtc crtc);
typedef void(*PFN_XRRFreeCrtcInfo)(XRRCrtcInfo* crtcInfo);
typedef Status(*PFN_XRRSetCrtcConfig)(Display* dpy,
		  XRRScreenResources* resources,
		  RRCrtc crtc,
		  Time timestamp,
		  int x, int y,
		  RRMode mode,
		  Rotation rotation,
		  RROutput* outputs,
		  int noutputs);
typedef int(*PFN_XRRGetCrtcGammaSize)(Display* dpy, RRCrtc crtc);
typedef XRRCrtcGamma*(*PFN_XRRGetCrtcGamma)(Display* dpy, RRCrtc crtc);
typedef XRRCrtcGamma*(*PFN_XRRAllocGamma)(int size);
typedef void(*PFN_XRRSetCrtcGamma)(Display* dpy, RRCrtc crtc, XRRCrtcGamma* gamma);
typedef void(*PFN_XRRFreeGamma)(XRRCrtcGamma* gamma);
typedef XRRScreenResources*(*PFN_XRRGetScreenResourcesCurrent)(Display* dpy, Window window);
typedef void(*PFN_XRRSetCrtcTransform)(Display* dpy,
		     RRCrtc	crtc,
		     XTransform* transform,
		     _Xconst char* filter,
		     XFixed* params,
		     int	nparams);
typedef Status(*PFN_XRRGetCrtcTransform)(Display* dpy,
		     RRCrtc	crtc,
		     XRRCrtcTransformAttributes** attributes);
typedef int(*PFN_XRRUpdateConfiguration)(XEvent* event);
typedef XRRPanning*(*PFN_XRRGetPanning)(Display* dpy, XRRScreenResources* resources, RRCrtc crtc);
typedef void(*PFN_XRRFreePanning)(XRRPanning* panning);
typedef Status(*PFN_XRRSetPanning)(Display* dpy,
	       XRRScreenResources* resources,
	       RRCrtc crtc,
	       XRRPanning* panning);
typedef void(*PFN_XRRSetOutputPrimary)(Display* dpy,
		    Window window,
		    RROutput output);
typedef RROutput(*PFN_XRRGetOutputPrimary)(Display* dpy,
		    Window window);
typedef XRRProviderResources*(*PFN_XRRGetProviderResources)(Display* dpy, Window window);
typedef void(*PFN_XRRFreeProviderResources)(XRRProviderResources* resources);
typedef XRRProviderInfo*(*PFN_XRRGetProviderInfo)(Display* dpy, XRRScreenResources* resources, RRProvider provider);
typedef void(*PFN_XRRFreeProviderInfo)(XRRProviderInfo* provider);
typedef int(*PFN_XRRSetProviderOutputSource)(Display* dpy, XID provider, XID source_provider);
typedef int(*PFN_XRRSetProviderOffloadSink)(Display* dpy, XID provider, XID sink_provider);
typedef Atom*(*PFN_XRRListProviderProperties)(Display* dpy, RRProvider provider, int* nprop);
typedef XRRPropertyInfo*(*PFN_XRRQueryProviderProperty)(Display* dpy, RRProvider provider, Atom property);
typedef void(*PFN_XRRConfigureProviderProperty)(Display* dpy, RRProvider provider, Atom property,
			    Bool pending, Bool range, int num_values,
			    long* values);
typedef void(*PFN_XRRChangeProviderProperty)(Display* dpy, RRProvider provider,
			 Atom property, Atom type,
			 int format, int mode,
			 _Xconst unsigned char* data, int nelements);
typedef void(*PFN_XRRDeleteProviderProperty)(Display* dpy, RRProvider provider, Atom property);
typedef int(*PFN_XRRGetProviderProperty)(Display* dpy, RRProvider provider,
			Atom property, long offset, long length,
			Bool _delete, Bool pending, Atom req_type,
			Atom* actual_type, int* actual_format,
			unsigned long* nitems, unsigned long* bytes_after,
			unsigned char** prop);
typedef XRRMonitorInfo*(*PFN_XRRAllocateMonitor)(Display* dpy, int noutput);
typedef XRRMonitorInfo*(*PFN_XRRGetMonitors)(Display* dpy, Window window, Bool get_active, int* nmonitors);
typedef void(*PFN_XRRSetMonitor)(Display* dpy, Window window, XRRMonitorInfo* monitor);
typedef void(*PFN_XRRDeleteMonitor)(Display* dpy, Window window, Atom name);
typedef void(*PFN_XRRFreeMonitors)(XRRMonitorInfo* monitors);
PFN_XRRQueryExtension src_XRRQueryExtension;
PFN_XRRQueryVersion src_XRRQueryVersion;
PFN_XRRGetScreenInfo src_XRRGetScreenInfo;
PFN_XRRFreeScreenConfigInfo src_XRRFreeScreenConfigInfo;
PFN_XRRSetScreenConfig src_XRRSetScreenConfig;
PFN_XRRSetScreenConfigAndRate src_XRRSetScreenConfigAndRate;
PFN_XRRConfigRotations src_XRRConfigRotations;
PFN_XRRConfigTimes src_XRRConfigTimes;
PFN_XRRConfigSizes src_XRRConfigSizes;
PFN_XRRConfigRates src_XRRConfigRates;
PFN_XRRConfigCurrentConfiguration src_XRRConfigCurrentConfiguration;
PFN_XRRConfigCurrentRate src_XRRConfigCurrentRate;
PFN_XRRRootToScreen src_XRRRootToScreen;
PFN_XRRSelectInput src_XRRSelectInput;
PFN_XRRRotations src_XRRRotations;
PFN_XRRSizes src_XRRSizes;
PFN_XRRRates src_XRRRates;
PFN_XRRTimes src_XRRTimes;
PFN_XRRGetScreenSizeRange src_XRRGetScreenSizeRange;
PFN_XRRSetScreenSize src_XRRSetScreenSize;
PFN_XRRGetScreenResources src_XRRGetScreenResources;
PFN_XRRFreeScreenResources src_XRRFreeScreenResources;
PFN_XRRGetOutputInfo src_XRRGetOutputInfo;
PFN_XRRFreeOutputInfo src_XRRFreeOutputInfo;
PFN_XRRListOutputProperties src_XRRListOutputProperties;
PFN_XRRQueryOutputProperty src_XRRQueryOutputProperty;
PFN_XRRConfigureOutputProperty src_XRRConfigureOutputProperty;
PFN_XRRChangeOutputProperty src_XRRChangeOutputProperty;
PFN_XRRDeleteOutputProperty src_XRRDeleteOutputProperty;
PFN_XRRGetOutputProperty src_XRRGetOutputProperty;
PFN_XRRAllocModeInfo src_XRRAllocModeInfo;
PFN_XRRCreateMode src_XRRCreateMode;
PFN_XRRDestroyMode src_XRRDestroyMode;
PFN_XRRAddOutputMode src_XRRAddOutputMode;
PFN_XRRDeleteOutputMode src_XRRDeleteOutputMode;
PFN_XRRFreeModeInfo src_XRRFreeModeInfo;
PFN_XRRGetCrtcInfo src_XRRGetCrtcInfo;
PFN_XRRFreeCrtcInfo src_XRRFreeCrtcInfo;
PFN_XRRSetCrtcConfig src_XRRSetCrtcConfig;
PFN_XRRGetCrtcGammaSize src_XRRGetCrtcGammaSize;
PFN_XRRGetCrtcGamma src_XRRGetCrtcGamma;
PFN_XRRAllocGamma src_XRRAllocGamma;
PFN_XRRSetCrtcGamma src_XRRSetCrtcGamma;
PFN_XRRFreeGamma src_XRRFreeGamma;
PFN_XRRGetScreenResourcesCurrent src_XRRGetScreenResourcesCurrent;
PFN_XRRSetCrtcTransform src_XRRSetCrtcTransform;
PFN_XRRGetCrtcTransform src_XRRGetCrtcTransform;
PFN_XRRUpdateConfiguration src_XRRUpdateConfiguration;
PFN_XRRGetPanning src_XRRGetPanning;
PFN_XRRFreePanning src_XRRFreePanning;
PFN_XRRSetPanning src_XRRSetPanning;
PFN_XRRSetOutputPrimary src_XRRSetOutputPrimary;
PFN_XRRGetOutputPrimary src_XRRGetOutputPrimary;
PFN_XRRGetProviderResources src_XRRGetProviderResources;
PFN_XRRFreeProviderResources src_XRRFreeProviderResources;
PFN_XRRGetProviderInfo src_XRRGetProviderInfo;
PFN_XRRFreeProviderInfo src_XRRFreeProviderInfo;
PFN_XRRSetProviderOutputSource src_XRRSetProviderOutputSource;
PFN_XRRSetProviderOffloadSink src_XRRSetProviderOffloadSink;
PFN_XRRListProviderProperties src_XRRListProviderProperties;
PFN_XRRQueryProviderProperty src_XRRQueryProviderProperty;
PFN_XRRConfigureProviderProperty src_XRRConfigureProviderProperty;
PFN_XRRChangeProviderProperty src_XRRChangeProviderProperty;
PFN_XRRDeleteProviderProperty src_XRRDeleteProviderProperty;
PFN_XRRGetProviderProperty src_XRRGetProviderProperty;
PFN_XRRAllocateMonitor src_XRRAllocateMonitor;
PFN_XRRGetMonitors src_XRRGetMonitors;
PFN_XRRSetMonitor src_XRRSetMonitor;
PFN_XRRDeleteMonitor src_XRRDeleteMonitor;
PFN_XRRFreeMonitors src_XRRFreeMonitors;
#define XRRQueryExtension src_XRRQueryExtension
#define XRRQueryVersion src_XRRQueryVersion
#define XRRGetScreenInfo src_XRRGetScreenInfo
#define XRRFreeScreenConfigInfo src_XRRFreeScreenConfigInfo
#define XRRSetScreenConfig src_XRRSetScreenConfig
#define XRRSetScreenConfigAndRate src_XRRSetScreenConfigAndRate
#define XRRConfigRotations src_XRRConfigRotations
#define XRRConfigTimes src_XRRConfigTimes
#define XRRConfigSizes src_XRRConfigSizes
#define XRRConfigRates src_XRRConfigRates
#define XRRConfigCurrentConfiguration src_XRRConfigCurrentConfiguration
#define XRRConfigCurrentRate src_XRRConfigCurrentRate
#define XRRRootToScreen src_XRRRootToScreen
#define XRRSelectInput src_XRRSelectInput
#define XRRRotations src_XRRRotations
#define XRRSizes src_XRRSizes
#define XRRRates src_XRRRates
#define XRRTimes src_XRRTimes
#define XRRGetScreenSizeRange src_XRRGetScreenSizeRange
#define XRRSetScreenSize src_XRRSetScreenSize
#define XRRGetScreenResources src_XRRGetScreenResources
#define XRRFreeScreenResources src_XRRFreeScreenResources
#define XRRGetOutputInfo src_XRRGetOutputInfo
#define XRRFreeOutputInfo src_XRRFreeOutputInfo
#define XRRListOutputProperties src_XRRListOutputProperties
#define XRRQueryOutputProperty src_XRRQueryOutputProperty
#define XRRConfigureOutputProperty src_XRRConfigureOutputProperty
#define XRRChangeOutputProperty src_XRRChangeOutputProperty
#define XRRDeleteOutputProperty src_XRRDeleteOutputProperty
#define XRRGetOutputProperty src_XRRGetOutputProperty
#define XRRAllocModeInfo src_XRRAllocModeInfo
#define XRRCreateMode src_XRRCreateMode
#define XRRDestroyMode src_XRRDestroyMode
#define XRRAddOutputMode src_XRRAddOutputMode
#define XRRDeleteOutputMode src_XRRDeleteOutputMode
#define XRRFreeModeInfo src_XRRFreeModeInfo
#define XRRGetCrtcInfo src_XRRGetCrtcInfo
#define XRRFreeCrtcInfo src_XRRFreeCrtcInfo
#define XRRSetCrtcConfig src_XRRSetCrtcConfig
#define XRRGetCrtcGammaSize src_XRRGetCrtcGammaSize
#define XRRGetCrtcGamma src_XRRGetCrtcGamma
#define XRRAllocGamma src_XRRAllocGamma
#define XRRSetCrtcGamma src_XRRSetCrtcGamma
#define XRRFreeGamma src_XRRFreeGamma
#define XRRGetScreenResourcesCurrent src_XRRGetScreenResourcesCurrent
#define XRRSetCrtcTransform src_XRRSetCrtcTransform
#define XRRGetCrtcTransform src_XRRGetCrtcTransform
#define XRRUpdateConfiguration src_XRRUpdateConfiguration
#define XRRGetPanning src_XRRGetPanning
#define XRRFreePanning src_XRRFreePanning
#define XRRSetPanning src_XRRSetPanning
#define XRRSetOutputPrimary src_XRRSetOutputPrimary
#define XRRGetOutputPrimary src_XRRGetOutputPrimary
#define XRRGetProviderResources src_XRRGetProviderResources
#define XRRFreeProviderResources src_XRRFreeProviderResources
#define XRRGetProviderInfo src_XRRGetProviderInfo
#define XRRFreeProviderInfo src_XRRFreeProviderInfo
#define XRRSetProviderOutputSource src_XRRSetProviderOutputSource
#define XRRSetProviderOffloadSink src_XRRSetProviderOffloadSink
#define XRRListProviderProperties src_XRRListProviderProperties
#define XRRQueryProviderProperty src_XRRQueryProviderProperty
#define XRRConfigureProviderProperty src_XRRConfigureProviderProperty
#define XRRChangeProviderProperty src_XRRChangeProviderProperty
#define XRRDeleteProviderProperty src_XRRDeleteProviderProperty
#define XRRGetProviderProperty src_XRRGetProviderProperty
#define XRRAllocateMonitor src_XRRAllocateMonitor
#define XRRGetMonitors src_XRRGetMonitors
#define XRRSetMonitor src_XRRSetMonitor
#define XRRDeleteMonitor src_XRRDeleteMonitor
#define XRRFreeMonitors src_XRRFreeMonitors
void loadXrandr(void* context, void *(*load_fn)(void* context, const char* name)) {
    src_XRRQueryExtension = (PFN_XRRQueryExtension)load_fn(context, "XRRQueryExtension");
    src_XRRQueryVersion = (PFN_XRRQueryVersion)load_fn(context, "XRRQueryVersion");
    src_XRRGetScreenInfo = (PFN_XRRGetScreenInfo)load_fn(context, "XRRGetScreenInfo");
    src_XRRFreeScreenConfigInfo = (PFN_XRRFreeScreenConfigInfo)load_fn(context, "XRRFreeScreenConfigInfo");
    src_XRRSetScreenConfig = (PFN_XRRSetScreenConfig)load_fn(context, "XRRSetScreenConfig");
    src_XRRSetScreenConfigAndRate = (PFN_XRRSetScreenConfigAndRate)load_fn(context, "XRRSetScreenConfigAndRate");
    src_XRRConfigRotations = (PFN_XRRConfigRotations)load_fn(context, "XRRConfigRotations");
    src_XRRConfigTimes = (PFN_XRRConfigTimes)load_fn(context, "XRRConfigTimes");
    src_XRRConfigSizes = (PFN_XRRConfigSizes)load_fn(context, "XRRConfigSizes");
    src_XRRConfigRates = (PFN_XRRConfigRates)load_fn(context, "XRRConfigRates");
    src_XRRConfigCurrentConfiguration = (PFN_XRRConfigCurrentConfiguration)load_fn(context, "XRRConfigCurrentConfiguration");
    src_XRRConfigCurrentRate = (PFN_XRRConfigCurrentRate)load_fn(context, "XRRConfigCurrentRate");
    src_XRRRootToScreen = (PFN_XRRRootToScreen)load_fn(context, "XRRRootToScreen");
    src_XRRSelectInput = (PFN_XRRSelectInput)load_fn(context, "XRRSelectInput");
    src_XRRRotations = (PFN_XRRRotations)load_fn(context, "XRRRotations");
    src_XRRSizes = (PFN_XRRSizes)load_fn(context, "XRRSizes");
    src_XRRRates = (PFN_XRRRates)load_fn(context, "XRRRates");
    src_XRRTimes = (PFN_XRRTimes)load_fn(context, "XRRTimes");
    src_XRRGetScreenSizeRange = (PFN_XRRGetScreenSizeRange)load_fn(context, "XRRGetScreenSizeRange");
    src_XRRSetScreenSize = (PFN_XRRSetScreenSize)load_fn(context, "XRRSetScreenSize");
    src_XRRGetScreenResources = (PFN_XRRGetScreenResources)load_fn(context, "XRRGetScreenResources");
    src_XRRFreeScreenResources = (PFN_XRRFreeScreenResources)load_fn(context, "XRRFreeScreenResources");
    src_XRRGetOutputInfo = (PFN_XRRGetOutputInfo)load_fn(context, "XRRGetOutputInfo");
    src_XRRFreeOutputInfo = (PFN_XRRFreeOutputInfo)load_fn(context, "XRRFreeOutputInfo");
    src_XRRListOutputProperties = (PFN_XRRListOutputProperties)load_fn(context, "XRRListOutputProperties");
    src_XRRQueryOutputProperty = (PFN_XRRQueryOutputProperty)load_fn(context, "XRRQueryOutputProperty");
    src_XRRConfigureOutputProperty = (PFN_XRRConfigureOutputProperty)load_fn(context, "XRRConfigureOutputProperty");
    src_XRRChangeOutputProperty = (PFN_XRRChangeOutputProperty)load_fn(context, "XRRChangeOutputProperty");
    src_XRRDeleteOutputProperty = (PFN_XRRDeleteOutputProperty)load_fn(context, "XRRDeleteOutputProperty");
    src_XRRGetOutputProperty = (PFN_XRRGetOutputProperty)load_fn(context, "XRRGetOutputProperty");
    src_XRRAllocModeInfo = (PFN_XRRAllocModeInfo)load_fn(context, "XRRAllocModeInfo");
    src_XRRCreateMode = (PFN_XRRCreateMode)load_fn(context, "XRRCreateMode");
    src_XRRDestroyMode = (PFN_XRRDestroyMode)load_fn(context, "XRRDestroyMode");
    src_XRRAddOutputMode = (PFN_XRRAddOutputMode)load_fn(context, "XRRAddOutputMode");
    src_XRRDeleteOutputMode = (PFN_XRRDeleteOutputMode)load_fn(context, "XRRDeleteOutputMode");
    src_XRRFreeModeInfo = (PFN_XRRFreeModeInfo)load_fn(context, "XRRFreeModeInfo");
    src_XRRGetCrtcInfo = (PFN_XRRGetCrtcInfo)load_fn(context, "XRRGetCrtcInfo");
    src_XRRFreeCrtcInfo = (PFN_XRRFreeCrtcInfo)load_fn(context, "XRRFreeCrtcInfo");
    src_XRRSetCrtcConfig = (PFN_XRRSetCrtcConfig)load_fn(context, "XRRSetCrtcConfig");
    src_XRRGetCrtcGammaSize = (PFN_XRRGetCrtcGammaSize)load_fn(context, "XRRGetCrtcGammaSize");
    src_XRRGetCrtcGamma = (PFN_XRRGetCrtcGamma)load_fn(context, "XRRGetCrtcGamma");
    src_XRRAllocGamma = (PFN_XRRAllocGamma)load_fn(context, "XRRAllocGamma");
    src_XRRSetCrtcGamma = (PFN_XRRSetCrtcGamma)load_fn(context, "XRRSetCrtcGamma");
    src_XRRFreeGamma = (PFN_XRRFreeGamma)load_fn(context, "XRRFreeGamma");
    src_XRRGetScreenResourcesCurrent = (PFN_XRRGetScreenResourcesCurrent)load_fn(context, "XRRGetScreenResourcesCurrent");
    src_XRRSetCrtcTransform = (PFN_XRRSetCrtcTransform)load_fn(context, "XRRSetCrtcTransform");
    src_XRRGetCrtcTransform = (PFN_XRRGetCrtcTransform)load_fn(context, "XRRGetCrtcTransform");
    src_XRRUpdateConfiguration = (PFN_XRRUpdateConfiguration)load_fn(context, "XRRUpdateConfiguration");
    src_XRRGetPanning = (PFN_XRRGetPanning)load_fn(context, "XRRGetPanning");
    src_XRRFreePanning = (PFN_XRRFreePanning)load_fn(context, "XRRFreePanning");
    src_XRRSetPanning = (PFN_XRRSetPanning)load_fn(context, "XRRSetPanning");
    src_XRRSetOutputPrimary = (PFN_XRRSetOutputPrimary)load_fn(context, "XRRSetOutputPrimary");
    src_XRRGetOutputPrimary = (PFN_XRRGetOutputPrimary)load_fn(context, "XRRGetOutputPrimary");
    src_XRRGetProviderResources = (PFN_XRRGetProviderResources)load_fn(context, "XRRGetProviderResources");
    src_XRRFreeProviderResources = (PFN_XRRFreeProviderResources)load_fn(context, "XRRFreeProviderResources");
    src_XRRGetProviderInfo = (PFN_XRRGetProviderInfo)load_fn(context, "XRRGetProviderInfo");
    src_XRRFreeProviderInfo = (PFN_XRRFreeProviderInfo)load_fn(context, "XRRFreeProviderInfo");
    src_XRRSetProviderOutputSource = (PFN_XRRSetProviderOutputSource)load_fn(context, "XRRSetProviderOutputSource");
    src_XRRSetProviderOffloadSink = (PFN_XRRSetProviderOffloadSink)load_fn(context, "XRRSetProviderOffloadSink");
    src_XRRListProviderProperties = (PFN_XRRListProviderProperties)load_fn(context, "XRRListProviderProperties");
    src_XRRQueryProviderProperty = (PFN_XRRQueryProviderProperty)load_fn(context, "XRRQueryProviderProperty");
    src_XRRConfigureProviderProperty = (PFN_XRRConfigureProviderProperty)load_fn(context, "XRRConfigureProviderProperty");
    src_XRRChangeProviderProperty = (PFN_XRRChangeProviderProperty)load_fn(context, "XRRChangeProviderProperty");
    src_XRRDeleteProviderProperty = (PFN_XRRDeleteProviderProperty)load_fn(context, "XRRDeleteProviderProperty");
    src_XRRGetProviderProperty = (PFN_XRRGetProviderProperty)load_fn(context, "XRRGetProviderProperty");
    src_XRRAllocateMonitor = (PFN_XRRAllocateMonitor)load_fn(context, "XRRAllocateMonitor");
    src_XRRGetMonitors = (PFN_XRRGetMonitors)load_fn(context, "XRRGetMonitors");
    src_XRRSetMonitor = (PFN_XRRSetMonitor)load_fn(context, "XRRSetMonitor");
    src_XRRDeleteMonitor = (PFN_XRRDeleteMonitor)load_fn(context, "XRRDeleteMonitor");
    src_XRRFreeMonitors = (PFN_XRRFreeMonitors)load_fn(context, "XRRFreeMonitors");
}